// Code generated by gen; DO NOT EDIT.

package sdk

import "net/http"

// Client is the mountOS Admin API client.
type Client struct {
	baseURL          string
	http             *http.Client
	auth             *tokenCache
	dashboardUser    *DashboardUser
	dashboardHMACKey string

	Accounts           *AccountsService
	Users              *UsersService
	Regions            *RegionsService
	Clusters           *ClustersService
	RegionClusters     *RegionClustersService
	Storages           *StoragesService
	Volumes            *VolumesService
	VolumeForkTrees    *VolumeForkTreesService
	VolumeForkEntries  *VolumeForkEntriesService
	VolumeForkSearches *VolumeForkSearchesService
	AuditLogs          *AuditLogsService
	RegionAuditLogs    *RegionAuditLogsService
	ServiceNodes       *ServiceNodesService
	Nodes              *NodesService
	ClientSessions     *ClientSessionsService
	Discover           *DiscoverService
	Dashboard          *DashboardService
	License            *LicenseService
	Alerts             *AlertsService
	RegionAlerts       *RegionAlertsService
	GCWorkerEvents     *GCWorkerEventsService
	Vault              *VaultService
}

// NewClient creates a new SDK client.
func NewClient(cfg Config) (*Client, error) {
	tc, err := newTokenCache(cfg.PrivateKey)
	if err != nil {
		return nil, err
	}

	c := &Client{
		baseURL:          cfg.BaseURL,
		http:             http.DefaultClient,
		auth:             tc,
		dashboardUser:    cfg.DashboardUser,
		dashboardHMACKey: cfg.DashboardHMACKey,
	}
	c.Accounts = &AccountsService{c: c}
	c.Users = &UsersService{c: c}
	c.Regions = &RegionsService{c: c}
	c.Clusters = &ClustersService{c: c}
	c.RegionClusters = &RegionClustersService{c: c}
	c.Storages = &StoragesService{c: c}
	c.Volumes = &VolumesService{c: c}
	c.VolumeForkTrees = &VolumeForkTreesService{c: c}
	c.VolumeForkEntries = &VolumeForkEntriesService{c: c}
	c.VolumeForkSearches = &VolumeForkSearchesService{c: c}
	c.AuditLogs = &AuditLogsService{c: c}
	c.RegionAuditLogs = &RegionAuditLogsService{c: c}
	c.ServiceNodes = &ServiceNodesService{c: c}
	c.Nodes = &NodesService{c: c}
	c.ClientSessions = &ClientSessionsService{c: c}
	c.Discover = &DiscoverService{c: c}
	c.Dashboard = &DashboardService{c: c}
	c.License = &LicenseService{c: c}
	c.Alerts = &AlertsService{c: c}
	c.RegionAlerts = &RegionAlertsService{c: c}
	c.GCWorkerEvents = &GCWorkerEventsService{c: c}
	c.Vault = &VaultService{c: c}
	return c, nil
}
