// Code generated by gen; DO NOT EDIT.

package sdk

import (
	"context"
	"fmt"
	"net/url"
	"strconv"
)

type AccountsService struct{ c *Client }

func (s *AccountsService) Create(ctx context.Context, req *CreateAccountRequest) (*IDResponse, error) {
	data, err := s.c.post(ctx, "/api/v1/accounts/create", req)
	if err != nil {
		return nil, err
	}
	return decodeJSON[IDResponse](data)
}

func (s *AccountsService) List(ctx context.Context, opts *AccountListOptions) (*PaginatedResponse[Account], error) {
	q := url.Values{}
	if opts != nil {
		if opts.IsActive != nil {
			q.Set("isActive", strconv.FormatBool(*opts.IsActive))
		}
		addPagination(q, opts.Page, opts.Limit)
	}
	path := "/api/v1/accounts/list"
	if qs := q.Encode(); qs != "" {
		path += "?" + qs
	}
	data, err := s.c.get(ctx, path)
	if err != nil {
		return nil, err
	}
	return decodeJSON[PaginatedResponse[Account]](data)
}

func (s *AccountsService) Get(ctx context.Context, accountID int64) (*Account, error) {
	data, err := s.c.get(ctx, fmt.Sprintf("/api/v1/accounts/%s", strconv.FormatInt(accountID, 10)))
	if err != nil {
		return nil, err
	}
	return decodeJSON[Account](data)
}

func (s *AccountsService) Edit(ctx context.Context, accountID int64, req *EditAccountRequest) (*IDResponse, error) {
	data, err := s.c.put(ctx, fmt.Sprintf("/api/v1/accounts/%s/edit", strconv.FormatInt(accountID, 10)), req)
	if err != nil {
		return nil, err
	}
	return decodeJSON[IDResponse](data)
}

func (s *AccountsService) Lock(ctx context.Context, accountID int64) (*IDResponse, error) {
	data, err := s.c.post(ctx, fmt.Sprintf("/api/v1/accounts/%s/lock", strconv.FormatInt(accountID, 10)), nil)
	if err != nil {
		return nil, err
	}
	return decodeJSON[IDResponse](data)
}

func (s *AccountsService) Unlock(ctx context.Context, accountID int64) (*IDResponse, error) {
	data, err := s.c.post(ctx, fmt.Sprintf("/api/v1/accounts/%s/unlock", strconv.FormatInt(accountID, 10)), nil)
	if err != nil {
		return nil, err
	}
	return decodeJSON[IDResponse](data)
}

func (s *AccountsService) Deactivate(ctx context.Context, accountID int64) (*IDResponse, error) {
	data, err := s.c.post(ctx, fmt.Sprintf("/api/v1/accounts/%s/deactivate", strconv.FormatInt(accountID, 10)), nil)
	if err != nil {
		return nil, err
	}
	return decodeJSON[IDResponse](data)
}

type UsersService struct{ c *Client }

func (s *UsersService) Add(ctx context.Context, req *AddUserRequest) (*IDResponse, error) {
	data, err := s.c.post(ctx, "/api/v1/users/add", req)
	if err != nil {
		return nil, err
	}
	return decodeJSON[IDResponse](data)
}

func (s *UsersService) List(ctx context.Context, opts *UserListOptions) (*PaginatedResponse[User], error) {
	q := url.Values{}
	if opts != nil {
		q.Set("accountId", strconv.FormatInt(opts.AccountID, 10))
		if opts.Search != "" {
			q.Set("search", opts.Search)
		}
		if opts.IsActive != nil {
			q.Set("isActive", strconv.FormatBool(*opts.IsActive))
		}
		addPagination(q, opts.Page, opts.Limit)
	}
	data, err := s.c.get(ctx, "/api/v1/users/list"+"?"+q.Encode())
	if err != nil {
		return nil, err
	}
	return decodeJSON[PaginatedResponse[User]](data)
}

func (s *UsersService) Get(ctx context.Context, userID int64) (*User, error) {
	data, err := s.c.get(ctx, fmt.Sprintf("/api/v1/users/%s", strconv.FormatInt(userID, 10)))
	if err != nil {
		return nil, err
	}
	return decodeJSON[User](data)
}

func (s *UsersService) Bulk(ctx context.Context, req *BulkUserRequest) (*BulkUserResponse, error) {
	data, err := s.c.post(ctx, "/api/v1/users/bulk", req)
	if err != nil {
		return nil, err
	}
	return decodeJSON[BulkUserResponse](data)
}

func (s *UsersService) Edit(ctx context.Context, userID int64, req *EditUserRequest) (*IDResponse, error) {
	data, err := s.c.put(ctx, fmt.Sprintf("/api/v1/users/%s/edit", strconv.FormatInt(userID, 10)), req)
	if err != nil {
		return nil, err
	}
	return decodeJSON[IDResponse](data)
}

func (s *UsersService) Deactivate(ctx context.Context, userID int64) (*IDResponse, error) {
	data, err := s.c.post(ctx, fmt.Sprintf("/api/v1/users/%s/deactivate", strconv.FormatInt(userID, 10)), nil)
	if err != nil {
		return nil, err
	}
	return decodeJSON[IDResponse](data)
}

type RegionsService struct{ c *Client }

func (s *RegionsService) Create(ctx context.Context, req *CreateRegionRequest) (*IDResponse, error) {
	data, err := s.c.post(ctx, "/api/v1/regions/create", req)
	if err != nil {
		return nil, err
	}
	return decodeJSON[IDResponse](data)
}

func (s *RegionsService) List(ctx context.Context, opts *RegionListOptions) (*PaginatedResponse[Region], error) {
	q := url.Values{}
	if opts != nil {
		if opts.IsActive != nil {
			q.Set("isActive", strconv.FormatBool(*opts.IsActive))
		}
		addPagination(q, opts.Page, opts.Limit)
	}
	path := "/api/v1/regions/list"
	if qs := q.Encode(); qs != "" {
		path += "?" + qs
	}
	data, err := s.c.get(ctx, path)
	if err != nil {
		return nil, err
	}
	return decodeJSON[PaginatedResponse[Region]](data)
}

func (s *RegionsService) Get(ctx context.Context, regionID int64) (*Region, error) {
	data, err := s.c.get(ctx, fmt.Sprintf("/api/v1/regions/%s", strconv.FormatInt(regionID, 10)))
	if err != nil {
		return nil, err
	}
	return decodeJSON[Region](data)
}

func (s *RegionsService) Edit(ctx context.Context, regionID int64, req *EditRegionRequest) (*IDResponse, error) {
	data, err := s.c.put(ctx, fmt.Sprintf("/api/v1/regions/%s/edit", strconv.FormatInt(regionID, 10)), req)
	if err != nil {
		return nil, err
	}
	return decodeJSON[IDResponse](data)
}

func (s *RegionsService) Deactivate(ctx context.Context, regionID int64) (*IDResponse, error) {
	data, err := s.c.post(ctx, fmt.Sprintf("/api/v1/regions/%s/deactivate", strconv.FormatInt(regionID, 10)), nil)
	if err != nil {
		return nil, err
	}
	return decodeJSON[IDResponse](data)
}

type RegionClustersService struct{ c *Client }

func (s *RegionClustersService) Create(ctx context.Context, regionID int64, req *CreateRegionClusterRequest) (*IDResponse, error) {
	data, err := s.c.post(ctx, fmt.Sprintf("/api/v1/regions/%s/clusters/create", strconv.FormatInt(regionID, 10)), req)
	if err != nil {
		return nil, err
	}
	return decodeJSON[IDResponse](data)
}

func (s *RegionClustersService) List(ctx context.Context, regionID int64, opts *RegionClusterListOptions) (*PaginatedResponse[RegionCluster], error) {
	q := url.Values{}
	if opts != nil {
		if opts.IsActive != nil {
			q.Set("isActive", strconv.FormatBool(*opts.IsActive))
		}
		addPagination(q, opts.Page, opts.Limit)
	}
	path := fmt.Sprintf("/api/v1/regions/%s/clusters/list", strconv.FormatInt(regionID, 10))
	if qs := q.Encode(); qs != "" {
		path += "?" + qs
	}
	data, err := s.c.get(ctx, path)
	if err != nil {
		return nil, err
	}
	return decodeJSON[PaginatedResponse[RegionCluster]](data)
}

func (s *RegionClustersService) Get(ctx context.Context, regionID int64, clusterID int64) (*RegionCluster, error) {
	data, err := s.c.get(ctx, fmt.Sprintf("/api/v1/regions/%s/clusters/%s", strconv.FormatInt(regionID, 10), strconv.FormatInt(clusterID, 10)))
	if err != nil {
		return nil, err
	}
	return decodeJSON[RegionCluster](data)
}

func (s *RegionClustersService) Edit(ctx context.Context, regionID int64, clusterID int64, req *EditRegionClusterRequest) (*IDResponse, error) {
	data, err := s.c.put(ctx, fmt.Sprintf("/api/v1/regions/%s/clusters/%s/edit", strconv.FormatInt(regionID, 10), strconv.FormatInt(clusterID, 10)), req)
	if err != nil {
		return nil, err
	}
	return decodeJSON[IDResponse](data)
}

func (s *RegionClustersService) SetDefault(ctx context.Context, regionID int64, clusterID int64) (*IDResponse, error) {
	data, err := s.c.post(ctx, fmt.Sprintf("/api/v1/regions/%s/clusters/%s/set-default", strconv.FormatInt(regionID, 10), strconv.FormatInt(clusterID, 10)), nil)
	if err != nil {
		return nil, err
	}
	return decodeJSON[IDResponse](data)
}

func (s *RegionClustersService) SetReady(ctx context.Context, regionID int64, clusterID int64, req *SetRegionClusterReadyRequest) (*SetReadyRegionClusterResponse, error) {
	data, err := s.c.post(ctx, fmt.Sprintf("/api/v1/regions/%s/clusters/%s/set-ready", strconv.FormatInt(regionID, 10), strconv.FormatInt(clusterID, 10)), req)
	if err != nil {
		return nil, err
	}
	return decodeJSON[SetReadyRegionClusterResponse](data)
}

func (s *RegionClustersService) Deactivate(ctx context.Context, regionID int64, clusterID int64) (*IDResponse, error) {
	data, err := s.c.post(ctx, fmt.Sprintf("/api/v1/regions/%s/clusters/%s/deactivate", strconv.FormatInt(regionID, 10), strconv.FormatInt(clusterID, 10)), nil)
	if err != nil {
		return nil, err
	}
	return decodeJSON[IDResponse](data)
}

type StoragesService struct{ c *Client }

func (s *StoragesService) Create(ctx context.Context, req *CreateStorageRequest) (*IDResponse, error) {
	data, err := s.c.post(ctx, "/api/v1/storages/create", req)
	if err != nil {
		return nil, err
	}
	return decodeJSON[IDResponse](data)
}

func (s *StoragesService) List(ctx context.Context, opts *StorageListOptions) (*PaginatedResponse[Storage], error) {
	q := url.Values{}
	if opts != nil {
		q.Set("accountId", strconv.FormatInt(opts.AccountID, 10))
		if opts.Search != "" {
			q.Set("search", opts.Search)
		}
		if opts.RegionID != nil {
			q.Set("regionId", strconv.FormatInt(*opts.RegionID, 10))
		}
		if opts.StorageType != "" {
			q.Set("storageType", opts.StorageType)
		}
		if opts.ProviderType != "" {
			q.Set("providerType", opts.ProviderType)
		}
		if opts.IsActive != nil {
			q.Set("isActive", strconv.FormatBool(*opts.IsActive))
		}
		addPagination(q, opts.Page, opts.Limit)
	}
	data, err := s.c.get(ctx, "/api/v1/storages/list"+"?"+q.Encode())
	if err != nil {
		return nil, err
	}
	return decodeJSON[PaginatedResponse[Storage]](data)
}

func (s *StoragesService) Get(ctx context.Context, storageID int64) (*Storage, error) {
	data, err := s.c.get(ctx, fmt.Sprintf("/api/v1/storages/%s", strconv.FormatInt(storageID, 10)))
	if err != nil {
		return nil, err
	}
	return decodeJSON[Storage](data)
}

func (s *StoragesService) Edit(ctx context.Context, storageID int64, req *EditStorageRequest) (*IDResponse, error) {
	data, err := s.c.put(ctx, fmt.Sprintf("/api/v1/storages/%s/edit", strconv.FormatInt(storageID, 10)), req)
	if err != nil {
		return nil, err
	}
	return decodeJSON[IDResponse](data)
}

func (s *StoragesService) Deactivate(ctx context.Context, storageID int64) (*IDResponse, error) {
	data, err := s.c.post(ctx, fmt.Sprintf("/api/v1/storages/%s/deactivate", strconv.FormatInt(storageID, 10)), nil)
	if err != nil {
		return nil, err
	}
	return decodeJSON[IDResponse](data)
}

func (s *StoragesService) TestBucket(ctx context.Context, req *TestStorageBucketRequest) (*TestBucketStorageResponse, error) {
	data, err := s.c.post(ctx, "/api/v1/storages/test-bucket", req)
	if err != nil {
		return nil, err
	}
	return decodeJSON[TestBucketStorageResponse](data)
}

func (s *StoragesService) TestStorageBucket(ctx context.Context, storageID int64) (*TestStorageBucketStorageResponse, error) {
	data, err := s.c.post(ctx, fmt.Sprintf("/api/v1/storages/%s/test-bucket", strconv.FormatInt(storageID, 10)), nil)
	if err != nil {
		return nil, err
	}
	return decodeJSON[TestStorageBucketStorageResponse](data)
}

type VolumesService struct{ c *Client }

func (s *VolumesService) Create(ctx context.Context, req *CreateVolumeRequest) (*CreateVolumeResponse, error) {
	data, err := s.c.post(ctx, "/api/v1/volumes/create", req)
	if err != nil {
		return nil, err
	}
	return decodeJSON[CreateVolumeResponse](data)
}

func (s *VolumesService) List(ctx context.Context, opts *VolumeListOptions) (*PaginatedResponse[Volume], error) {
	q := url.Values{}
	if opts != nil {
		q.Set("accountId", strconv.FormatInt(opts.AccountID, 10))
		if opts.RegionID != nil {
			q.Set("regionId", strconv.FormatInt(*opts.RegionID, 10))
		}
		if opts.RegionClusterID != nil {
			q.Set("regionClusterId", strconv.FormatInt(*opts.RegionClusterID, 10))
		}
		if opts.StorageID != nil {
			q.Set("storageId", strconv.FormatInt(*opts.StorageID, 10))
		}
		if opts.VolumeType != "" {
			q.Set("volumeType", opts.VolumeType)
		}
		if opts.Locked != nil {
			q.Set("locked", strconv.FormatBool(*opts.Locked))
		}
		if opts.IsActive != nil {
			q.Set("isActive", strconv.FormatBool(*opts.IsActive))
		}
		addPagination(q, opts.Page, opts.Limit)
	}
	data, err := s.c.get(ctx, "/api/v1/volumes/list"+"?"+q.Encode())
	if err != nil {
		return nil, err
	}
	return decodeJSON[PaginatedResponse[Volume]](data)
}

func (s *VolumesService) Get(ctx context.Context, volumeID int64) (*Volume, error) {
	data, err := s.c.get(ctx, fmt.Sprintf("/api/v1/volumes/%s", strconv.FormatInt(volumeID, 10)))
	if err != nil {
		return nil, err
	}
	return decodeJSON[Volume](data)
}

func (s *VolumesService) Edit(ctx context.Context, volumeID int64, req *EditVolumeRequest) (*IDResponse, error) {
	data, err := s.c.put(ctx, fmt.Sprintf("/api/v1/volumes/%s/edit", strconv.FormatInt(volumeID, 10)), req)
	if err != nil {
		return nil, err
	}
	return decodeJSON[IDResponse](data)
}

func (s *VolumesService) Lock(ctx context.Context, volumeID int64) (*IDResponse, error) {
	data, err := s.c.post(ctx, fmt.Sprintf("/api/v1/volumes/%s/lock", strconv.FormatInt(volumeID, 10)), nil)
	if err != nil {
		return nil, err
	}
	return decodeJSON[IDResponse](data)
}

func (s *VolumesService) Unlock(ctx context.Context, volumeID int64) (*IDResponse, error) {
	data, err := s.c.post(ctx, fmt.Sprintf("/api/v1/volumes/%s/unlock", strconv.FormatInt(volumeID, 10)), nil)
	if err != nil {
		return nil, err
	}
	return decodeJSON[IDResponse](data)
}

func (s *VolumesService) MoveCluster(ctx context.Context, volumeID int64, req *MoveVolumeClusterRequest) (*MoveClusterVolumeResponse, error) {
	data, err := s.c.post(ctx, fmt.Sprintf("/api/v1/volumes/%s/move-cluster", strconv.FormatInt(volumeID, 10)), req)
	if err != nil {
		return nil, err
	}
	return decodeJSON[MoveClusterVolumeResponse](data)
}

func (s *VolumesService) Deactivate(ctx context.Context, volumeID int64, req *DeactivateVolumeRequest) (*IDResponse, error) {
	data, err := s.c.post(ctx, fmt.Sprintf("/api/v1/volumes/%s/deactivate", strconv.FormatInt(volumeID, 10)), req)
	if err != nil {
		return nil, err
	}
	return decodeJSON[IDResponse](data)
}

func (s *VolumesService) Activate(ctx context.Context, volumeID int64) (*IDResponse, error) {
	data, err := s.c.post(ctx, fmt.Sprintf("/api/v1/volumes/%s/activate", strconv.FormatInt(volumeID, 10)), nil)
	if err != nil {
		return nil, err
	}
	return decodeJSON[IDResponse](data)
}

func (s *VolumesService) GenerateAPIKeys(ctx context.Context, volumeID int64, req *GenerateVolumeAPIKeysRequest) (*GenerateAPIKeysVolumeResponse, error) {
	data, err := s.c.post(ctx, fmt.Sprintf("/api/v1/volumes/%s/api-keys/generate", strconv.FormatInt(volumeID, 10)), req)
	if err != nil {
		return nil, err
	}
	return decodeJSON[GenerateAPIKeysVolumeResponse](data)
}

func (s *VolumesService) RevokeAPIKey(ctx context.Context, volumeID int64, req *RevokeVolumeAPIKeyRequest) error {
	_, err := s.c.post(ctx, fmt.Sprintf("/api/v1/volumes/%s/api-keys/revoke", strconv.FormatInt(volumeID, 10)), req)
	return err
}

func (s *VolumesService) RevokeAPIKeysByUser(ctx context.Context, volumeID int64, req *RevokeVolumeAPIKeysByUserRequest) error {
	_, err := s.c.post(ctx, fmt.Sprintf("/api/v1/volumes/%s/api-keys/revoke-by-user", strconv.FormatInt(volumeID, 10)), req)
	return err
}

func (s *VolumesService) UpdateQuota(ctx context.Context, volumeID int64, req *UpdateVolumeQuotaRequest) (*IDResponse, error) {
	data, err := s.c.put(ctx, fmt.Sprintf("/api/v1/volumes/%s/quota", strconv.FormatInt(volumeID, 10)), req)
	if err != nil {
		return nil, err
	}
	return decodeJSON[IDResponse](data)
}

func (s *VolumesService) Stats(ctx context.Context, volumeID int64) (*StatsVolumeResponse, error) {
	data, err := s.c.get(ctx, fmt.Sprintf("/api/v1/volumes/%s/stats", strconv.FormatInt(volumeID, 10)))
	if err != nil {
		return nil, err
	}
	return decodeJSON[StatsVolumeResponse](data)
}

func (s *VolumesService) SizeHistory(ctx context.Context, volumeID int64, from string, to string) (*SizeHistoryVolumeResponse, error) {
	q := url.Values{}
	q.Set("from", from)
	q.Set("to", to)
	data, err := s.c.get(ctx, fmt.Sprintf("/api/v1/volumes/%s/size-history", strconv.FormatInt(volumeID, 10))+"?"+q.Encode())
	if err != nil {
		return nil, err
	}
	return decodeJSON[SizeHistoryVolumeResponse](data)
}

func (s *VolumesService) CreateFork(ctx context.Context, volumeID int64, req *CreateVolumeForkRequest) (*Fork, error) {
	data, err := s.c.post(ctx, fmt.Sprintf("/api/v1/volumes/%s/forks/create", strconv.FormatInt(volumeID, 10)), req)
	if err != nil {
		return nil, err
	}
	return decodeJSON[Fork](data)
}

func (s *VolumesService) ListForks(ctx context.Context, volumeID int64, volumeType string) ([]Fork, error) {
	q := url.Values{}
	if volumeType != "" {
		q.Set("volumeType", volumeType)
	}
	path := fmt.Sprintf("/api/v1/volumes/%s/forks", strconv.FormatInt(volumeID, 10))
	if qs := q.Encode(); qs != "" {
		path += "?" + qs
	}
	data, err := s.c.get(ctx, path)
	if err != nil {
		return nil, err
	}
	result, err := decodeJSON[[]Fork](data)
	if err != nil {
		return nil, err
	}
	return *result, nil
}

func (s *VolumesService) ListAllForks(ctx context.Context, volumeID int64, volumeType string) ([]Fork, error) {
	q := url.Values{}
	if volumeType != "" {
		q.Set("volumeType", volumeType)
	}
	path := fmt.Sprintf("/api/v1/volumes/%s/forks?include_inactive=true", strconv.FormatInt(volumeID, 10))
	if qs := q.Encode(); qs != "" {
		path += "?" + qs
	}
	data, err := s.c.get(ctx, path)
	if err != nil {
		return nil, err
	}
	result, err := decodeJSON[[]Fork](data)
	if err != nil {
		return nil, err
	}
	return *result, nil
}

func (s *VolumesService) DeleteFork(ctx context.Context, volumeID int64, forkName string, req *DeleteVolumeForkRequest) (*DeleteForkVolumeResponse, error) {
	data, err := s.c.post(ctx, fmt.Sprintf("/api/v1/volumes/%s/forks/%s/delete", strconv.FormatInt(volumeID, 10), forkName), req)
	if err != nil {
		return nil, err
	}
	return decodeJSON[DeleteForkVolumeResponse](data)
}

func (s *VolumesService) RestoreFork(ctx context.Context, volumeID int64, forkName string, req *RestoreVolumeForkRequest) (*Fork, error) {
	data, err := s.c.post(ctx, fmt.Sprintf("/api/v1/volumes/%s/forks/%s/restore", strconv.FormatInt(volumeID, 10), forkName), req)
	if err != nil {
		return nil, err
	}
	return decodeJSON[Fork](data)
}

type VolumeForkTreesService struct{ c *Client }

func (s *VolumeForkTreesService) List(ctx context.Context, volumeID int64, forkName string, opts *VolumeForkTreeListOptions) (*CursorPaginatedResponse[ForkTreeEntry], error) {
	q := url.Values{}
	if opts != nil {
		if opts.Path != "" {
			q.Set("path", opts.Path)
		}
		if opts.AsOf != nil {
			q.Set("asOf", strconv.FormatInt(*opts.AsOf, 10))
		}
		if opts.Cursor > 0 {
			q.Set("cursor", strconv.FormatInt(opts.Cursor, 10))
		}
		if opts.Limit > 0 {
			q.Set("limit", strconv.Itoa(opts.Limit))
		}
		if opts.Sort != "" {
			q.Set("sort", opts.Sort)
		}
		if opts.Kind != "" {
			q.Set("kind", opts.Kind)
		}
	}
	path := fmt.Sprintf("/api/v1/volumes/%s/forks/%s/tree", strconv.FormatInt(volumeID, 10), forkName)
	if qs := q.Encode(); qs != "" {
		path += "?" + qs
	}
	data, err := s.c.get(ctx, path)
	if err != nil {
		return nil, err
	}
	return decodeJSON[CursorPaginatedResponse[ForkTreeEntry]](data)
}

type VolumeForkEntriesService struct{ c *Client }

func (s *VolumeForkEntriesService) Get(ctx context.Context, volumeID int64, forkName string, path string, inode int64, asOf int64) (*ForkEntryDetail, error) {
	q := url.Values{}
	q.Set("path", path)
	q.Set("inode", strconv.FormatInt(inode, 10))
	q.Set("asOf", strconv.FormatInt(asOf, 10))
	data, err := s.c.get(ctx, fmt.Sprintf("/api/v1/volumes/%s/forks/%s/entry", strconv.FormatInt(volumeID, 10), forkName)+"?"+q.Encode())
	if err != nil {
		return nil, err
	}
	return decodeJSON[ForkEntryDetail](data)
}

func (s *VolumeForkEntriesService) Versions(ctx context.Context, volumeID int64, forkName string, opts *VolumeForkEntryListOptions) (*CursorPaginatedResponse[ForkEntryVersion], error) {
	q := url.Values{}
	if opts != nil {
		if opts.Path != "" {
			q.Set("path", opts.Path)
		}
		if opts.Cursor > 0 {
			q.Set("cursor", strconv.FormatInt(opts.Cursor, 10))
		}
		if opts.Limit > 0 {
			q.Set("limit", strconv.Itoa(opts.Limit))
		}
	}
	path := fmt.Sprintf("/api/v1/volumes/%s/forks/%s/entry/versions", strconv.FormatInt(volumeID, 10), forkName)
	if qs := q.Encode(); qs != "" {
		path += "?" + qs
	}
	data, err := s.c.get(ctx, path)
	if err != nil {
		return nil, err
	}
	return decodeJSON[CursorPaginatedResponse[ForkEntryVersion]](data)
}

type VolumeForkSearchesService struct{ c *Client }

func (s *VolumeForkSearchesService) Find(ctx context.Context, volumeID int64, forkName string, opts *VolumeForkSearchListOptions) (*CursorPaginatedResponse[ForkTreeMatch], error) {
	q := url.Values{}
	if opts != nil {
		if opts.Q != "" {
			q.Set("q", opts.Q)
		}
		if opts.Path != "" {
			q.Set("path", opts.Path)
		}
		if opts.AsOf != nil {
			q.Set("asOf", strconv.FormatInt(*opts.AsOf, 10))
		}
		if opts.Exact != nil {
			q.Set("exact", strconv.FormatBool(*opts.Exact))
		}
		if opts.Cursor > 0 {
			q.Set("cursor", strconv.FormatInt(opts.Cursor, 10))
		}
		if opts.Limit > 0 {
			q.Set("limit", strconv.Itoa(opts.Limit))
		}
		if opts.Kind != "" {
			q.Set("kind", opts.Kind)
		}
	}
	path := fmt.Sprintf("/api/v1/volumes/%s/forks/%s/search", strconv.FormatInt(volumeID, 10), forkName)
	if qs := q.Encode(); qs != "" {
		path += "?" + qs
	}
	data, err := s.c.get(ctx, path)
	if err != nil {
		return nil, err
	}
	return decodeJSON[CursorPaginatedResponse[ForkTreeMatch]](data)
}

type AuditLogsService struct{ c *Client }

func (s *AuditLogsService) List(ctx context.Context, opts *AuditLogListOptions) (*CursorPaginatedResponse[AuditLog], error) {
	q := url.Values{}
	if opts != nil {
		if opts.AccountID != nil {
			q.Set("accountId", strconv.FormatInt(*opts.AccountID, 10))
		}
		if opts.RegionID != nil {
			q.Set("regionId", strconv.FormatInt(*opts.RegionID, 10))
		}
		if opts.RegionClusterID != nil {
			q.Set("regionClusterId", strconv.FormatInt(*opts.RegionClusterID, 10))
		}
		if opts.Cursor > 0 {
			q.Set("cursor", strconv.FormatInt(opts.Cursor, 10))
		}
		if opts.Limit > 0 {
			q.Set("limit", strconv.Itoa(opts.Limit))
		}
		if opts.Subject != "" {
			q.Set("subject", opts.Subject)
		}
	}
	path := "/api/v1/audit-logs/list"
	if qs := q.Encode(); qs != "" {
		path += "?" + qs
	}
	data, err := s.c.get(ctx, path)
	if err != nil {
		return nil, err
	}
	return decodeJSON[CursorPaginatedResponse[AuditLog]](data)
}

type RegionAuditLogsService struct{ c *Client }

func (s *RegionAuditLogsService) List(ctx context.Context, regionID int64, opts *RegionAuditLogListOptions) (*CursorPaginatedResponse[AuditLog], error) {
	q := url.Values{}
	if opts != nil {
		if opts.RegionClusterID != nil {
			q.Set("regionClusterId", strconv.FormatInt(*opts.RegionClusterID, 10))
		}
		if opts.Cursor > 0 {
			q.Set("cursor", strconv.FormatInt(opts.Cursor, 10))
		}
		if opts.Limit > 0 {
			q.Set("limit", strconv.Itoa(opts.Limit))
		}
		if opts.Subject != "" {
			q.Set("subject", opts.Subject)
		}
		if opts.Node != "" {
			q.Set("node", opts.Node)
		}
	}
	path := fmt.Sprintf("/api/v1/regions/%s/audit-logs/list", strconv.FormatInt(regionID, 10))
	if qs := q.Encode(); qs != "" {
		path += "?" + qs
	}
	data, err := s.c.get(ctx, path)
	if err != nil {
		return nil, err
	}
	return decodeJSON[CursorPaginatedResponse[AuditLog]](data)
}

type ServiceNodesService struct{ c *Client }

func (s *ServiceNodesService) List(ctx context.Context, regionID int64, serviceType string, status string, inactiveHours int, regionClusterID int64) ([]ServiceNode, error) {
	q := url.Values{}
	if serviceType != "" {
		q.Set("serviceType", serviceType)
	}
	if status != "" {
		q.Set("status", status)
	}
	if inactiveHours != 0 {
		q.Set("inactiveHours", strconv.Itoa(inactiveHours))
	}
	if regionClusterID != 0 {
		q.Set("regionClusterId", strconv.FormatInt(regionClusterID, 10))
	}
	path := fmt.Sprintf("/api/v1/regions/%s/nodes", strconv.FormatInt(regionID, 10))
	if qs := q.Encode(); qs != "" {
		path += "?" + qs
	}
	data, err := s.c.get(ctx, path)
	if err != nil {
		return nil, err
	}
	result, err := decodeJSON[[]ServiceNode](data)
	if err != nil {
		return nil, err
	}
	return *result, nil
}

func (s *ServiceNodesService) Stats(ctx context.Context, regionID int64, nodeID string) (*string, error) {
	data, err := s.c.get(ctx, fmt.Sprintf("/api/v1/regions/%s/nodes/%s/stats", strconv.FormatInt(regionID, 10), url.PathEscape(nodeID)))
	if err != nil {
		return nil, err
	}
	return decodeJSON[string](data)
}

type NodesService struct{ c *Client }

func (s *NodesService) ListAll(ctx context.Context, serviceType string, status string, inactiveHours int) ([]ServiceNode, error) {
	q := url.Values{}
	if serviceType != "" {
		q.Set("serviceType", serviceType)
	}
	if status != "" {
		q.Set("status", status)
	}
	if inactiveHours != 0 {
		q.Set("inactiveHours", strconv.Itoa(inactiveHours))
	}
	path := "/api/v1/nodes"
	if qs := q.Encode(); qs != "" {
		path += "?" + qs
	}
	data, err := s.c.get(ctx, path)
	if err != nil {
		return nil, err
	}
	result, err := decodeJSON[[]ServiceNode](data)
	if err != nil {
		return nil, err
	}
	return *result, nil
}

type ClientSessionsService struct{ c *Client }

func (s *ClientSessionsService) List(ctx context.Context, opts *ClientSessionListOptions) (*PaginatedResponse[ClientSession], error) {
	q := url.Values{}
	if opts != nil {
		if opts.AccountID != nil {
			q.Set("accountId", strconv.FormatInt(*opts.AccountID, 10))
		}
		if opts.RegionID != nil {
			q.Set("regionId", strconv.FormatInt(*opts.RegionID, 10))
		}
		if opts.RegionClusterID != nil {
			q.Set("regionClusterId", strconv.FormatInt(*opts.RegionClusterID, 10))
		}
		if opts.VolumeID != nil {
			q.Set("volumeId", strconv.FormatInt(*opts.VolumeID, 10))
		}
		if opts.UserID != nil {
			q.Set("userId", strconv.FormatInt(*opts.UserID, 10))
		}
		if opts.ClientType != "" {
			q.Set("clientType", opts.ClientType)
		}
		if opts.Status != "" {
			q.Set("status", opts.Status)
		}
		if opts.IsActive != "" {
			q.Set("isActive", opts.IsActive)
		}
		if opts.OsName != "" {
			q.Set("osName", opts.OsName)
		}
		if opts.Platform != "" {
			q.Set("platform", opts.Platform)
		}
		if opts.Search != "" {
			q.Set("search", opts.Search)
		}
		addPagination(q, opts.Page, opts.Limit)
	}
	path := "/api/v1/client-sessions/list"
	if qs := q.Encode(); qs != "" {
		path += "?" + qs
	}
	data, err := s.c.get(ctx, path)
	if err != nil {
		return nil, err
	}
	return decodeJSON[PaginatedResponse[ClientSession]](data)
}

func (s *ClientSessionsService) Get(ctx context.Context, sessionID int64) (*ClientSession, error) {
	data, err := s.c.get(ctx, fmt.Sprintf("/api/v1/client-sessions/%s", strconv.FormatInt(sessionID, 10)))
	if err != nil {
		return nil, err
	}
	return decodeJSON[ClientSession](data)
}

func (s *ClientSessionsService) Summary(ctx context.Context, accountID int64, regionID int64, regionClusterID int64, volumeID int64) (*SessionSummary, error) {
	q := url.Values{}
	q.Set("accountId", strconv.FormatInt(accountID, 10))
	q.Set("regionId", strconv.FormatInt(regionID, 10))
	q.Set("regionClusterId", strconv.FormatInt(regionClusterID, 10))
	q.Set("volumeId", strconv.FormatInt(volumeID, 10))
	data, err := s.c.get(ctx, "/api/v1/client-sessions/summary"+"?"+q.Encode())
	if err != nil {
		return nil, err
	}
	return decodeJSON[SessionSummary](data)
}

type DiscoverService struct{ c *Client }

func (s *DiscoverService) Meta(ctx context.Context, accessKeyID string) (*DiscoverMetaResponse, error) {
	q := url.Values{}
	q.Set("access_key_id", accessKeyID)
	data, err := s.c.get(ctx, "/api/v1/discover/meta"+"?"+q.Encode())
	if err != nil {
		return nil, err
	}
	return decodeJSON[DiscoverMetaResponse](data)
}

type DashboardService struct{ c *Client }

func (s *DashboardService) Stats(ctx context.Context, accountID int64) (*DashboardStats, error) {
	q := url.Values{}
	q.Set("accountId", strconv.FormatInt(accountID, 10))
	data, err := s.c.get(ctx, "/api/v1/dashboard/stats"+"?"+q.Encode())
	if err != nil {
		return nil, err
	}
	return decodeJSON[DashboardStats](data)
}

type LicenseService struct{ c *Client }

func (s *LicenseService) Get(ctx context.Context) (*LicenseDetails, error) {
	data, err := s.c.get(ctx, "/api/v1/license")
	if err != nil {
		return nil, err
	}
	return decodeJSON[LicenseDetails](data)
}

func (s *LicenseService) Terms(ctx context.Context) (*LicenseTerms, error) {
	data, err := s.c.get(ctx, "/api/v1/license/terms")
	if err != nil {
		return nil, err
	}
	return decodeJSON[LicenseTerms](data)
}

type AlertsService struct{ c *Client }

func (s *AlertsService) List(ctx context.Context, opts *AlertListOptions) (*PaginatedResponse[ServiceAlert], error) {
	q := url.Values{}
	if opts != nil {
		if opts.Active != nil {
			q.Set("active", strconv.FormatBool(*opts.Active))
		}
		if opts.AccountID != nil {
			q.Set("accountId", strconv.FormatInt(*opts.AccountID, 10))
		}
		if opts.RegionID != nil {
			q.Set("regionId", strconv.FormatInt(*opts.RegionID, 10))
		}
		if opts.Severity != nil {
			q.Set("severity", strconv.Itoa(*opts.Severity))
		}
		if opts.Category != "" {
			q.Set("category", opts.Category)
		}
		if opts.Since != "" {
			q.Set("since", opts.Since)
		}
		addPagination(q, opts.Page, opts.Limit)
	}
	path := "/api/v1/alerts/list"
	if qs := q.Encode(); qs != "" {
		path += "?" + qs
	}
	data, err := s.c.get(ctx, path)
	if err != nil {
		return nil, err
	}
	return decodeJSON[PaginatedResponse[ServiceAlert]](data)
}

func (s *AlertsService) Count(ctx context.Context) (*AlertCountResponse, error) {
	data, err := s.c.get(ctx, "/api/v1/alerts/count")
	if err != nil {
		return nil, err
	}
	return decodeJSON[AlertCountResponse](data)
}

func (s *AlertsService) Resolve(ctx context.Context, alertID string) error {
	_, err := s.c.post(ctx, fmt.Sprintf("/api/v1/alerts/%s/resolve", alertID), nil)
	return err
}

type RegionAlertsService struct{ c *Client }

func (s *RegionAlertsService) List(ctx context.Context, regionID int64, opts *RegionAlertListOptions) (*PaginatedResponse[RegionAlert], error) {
	q := url.Values{}
	if opts != nil {
		if opts.Active != nil {
			q.Set("active", strconv.FormatBool(*opts.Active))
		}
		if opts.Severity != nil {
			q.Set("severity", strconv.Itoa(*opts.Severity))
		}
		if opts.Category != "" {
			q.Set("category", opts.Category)
		}
		if opts.NodeID != "" {
			q.Set("nodeId", opts.NodeID)
		}
		if opts.RegionClusterID != nil {
			q.Set("regionClusterId", strconv.FormatInt(*opts.RegionClusterID, 10))
		}
		if opts.Since != "" {
			q.Set("since", opts.Since)
		}
		addPagination(q, opts.Page, opts.Limit)
	}
	path := fmt.Sprintf("/api/v1/regions/%s/alerts/list", strconv.FormatInt(regionID, 10))
	if qs := q.Encode(); qs != "" {
		path += "?" + qs
	}
	data, err := s.c.get(ctx, path)
	if err != nil {
		return nil, err
	}
	return decodeJSON[PaginatedResponse[RegionAlert]](data)
}

func (s *RegionAlertsService) Count(ctx context.Context, regionID int64, regionClusterID int64) (*AlertCountResponse, error) {
	q := url.Values{}
	q.Set("regionClusterId", strconv.FormatInt(regionClusterID, 10))
	data, err := s.c.get(ctx, fmt.Sprintf("/api/v1/regions/%s/alerts/count", strconv.FormatInt(regionID, 10))+"?"+q.Encode())
	if err != nil {
		return nil, err
	}
	return decodeJSON[AlertCountResponse](data)
}

func (s *RegionAlertsService) Resolve(ctx context.Context, regionID int64, alertID string) error {
	_, err := s.c.post(ctx, fmt.Sprintf("/api/v1/regions/%s/alerts/%s/resolve", strconv.FormatInt(regionID, 10), alertID), nil)
	return err
}

type VaultService struct{ c *Client }

func (s *VaultService) Resync(ctx context.Context) error {
	_, err := s.c.post(ctx, "/api/v1/vault/resync", nil)
	return err
}
