// Code generated by gen; DO NOT EDIT.

package sdk

import (
	"context"
	"fmt"
	"net/url"
	"strconv"
)

type AccountsService struct{ c *Client }

func (s *AccountsService) Create(ctx context.Context, req *CreateAccountRequest) (*IDResponse, error) {
	data, err := s.c.post(ctx, "/api/v1/accounts/create", req)
	if err != nil {
		return nil, err
	}
	return decodeJSON[IDResponse](data)
}

func (s *AccountsService) List(ctx context.Context, opts *ListOptions) (*PaginatedResponse[Account], error) {
	q := url.Values{}
	if opts != nil {
		addPagination(q, opts.Page, opts.Limit)
	}
	path := "/api/v1/accounts/list"
	if qs := q.Encode(); qs != "" {
		path += "?" + qs
	}
	data, err := s.c.get(ctx, path)
	if err != nil {
		return nil, err
	}
	return decodeJSON[PaginatedResponse[Account]](data)
}

func (s *AccountsService) Get(ctx context.Context, accountID int64) (*Account, error) {
	data, err := s.c.get(ctx, fmt.Sprintf("/api/v1/accounts/%s", strconv.FormatInt(accountID, 10)))
	if err != nil {
		return nil, err
	}
	return decodeJSON[Account](data)
}

func (s *AccountsService) Edit(ctx context.Context, accountID int64, req *EditAccountRequest) (*IDResponse, error) {
	data, err := s.c.put(ctx, fmt.Sprintf("/api/v1/accounts/%s/edit", strconv.FormatInt(accountID, 10)), req)
	if err != nil {
		return nil, err
	}
	return decodeJSON[IDResponse](data)
}

func (s *AccountsService) Lock(ctx context.Context, accountID int64) (*IDResponse, error) {
	data, err := s.c.post(ctx, fmt.Sprintf("/api/v1/accounts/%s/lock", strconv.FormatInt(accountID, 10)), nil)
	if err != nil {
		return nil, err
	}
	return decodeJSON[IDResponse](data)
}

func (s *AccountsService) Unlock(ctx context.Context, accountID int64) (*IDResponse, error) {
	data, err := s.c.post(ctx, fmt.Sprintf("/api/v1/accounts/%s/unlock", strconv.FormatInt(accountID, 10)), nil)
	if err != nil {
		return nil, err
	}
	return decodeJSON[IDResponse](data)
}

func (s *AccountsService) Activate(ctx context.Context, accountID int64) (*IDResponse, error) {
	data, err := s.c.post(ctx, fmt.Sprintf("/api/v1/accounts/%s/activate", strconv.FormatInt(accountID, 10)), nil)
	if err != nil {
		return nil, err
	}
	return decodeJSON[IDResponse](data)
}

func (s *AccountsService) Deactivate(ctx context.Context, accountID int64) (*IDResponse, error) {
	data, err := s.c.post(ctx, fmt.Sprintf("/api/v1/accounts/%s/deactivate", strconv.FormatInt(accountID, 10)), nil)
	if err != nil {
		return nil, err
	}
	return decodeJSON[IDResponse](data)
}

type UsersService struct{ c *Client }

func (s *UsersService) Add(ctx context.Context, req *AddUserRequest) (*IDResponse, error) {
	data, err := s.c.post(ctx, "/api/v1/users/add", req)
	if err != nil {
		return nil, err
	}
	return decodeJSON[IDResponse](data)
}

func (s *UsersService) List(ctx context.Context, opts *UserListOptions) (*PaginatedResponse[User], error) {
	q := url.Values{}
	if opts != nil {
		q.Set("accountId", strconv.FormatInt(opts.AccountID, 10))
		addPagination(q, opts.Page, opts.Limit)
	}
	data, err := s.c.get(ctx, "/api/v1/users/list"+"?"+q.Encode())
	if err != nil {
		return nil, err
	}
	return decodeJSON[PaginatedResponse[User]](data)
}

func (s *UsersService) Get(ctx context.Context, userID int64) (*User, error) {
	data, err := s.c.get(ctx, fmt.Sprintf("/api/v1/users/%s", strconv.FormatInt(userID, 10)))
	if err != nil {
		return nil, err
	}
	return decodeJSON[User](data)
}

func (s *UsersService) Edit(ctx context.Context, userID int64, req *EditUserRequest) (*IDResponse, error) {
	data, err := s.c.put(ctx, fmt.Sprintf("/api/v1/users/%s/edit", strconv.FormatInt(userID, 10)), req)
	if err != nil {
		return nil, err
	}
	return decodeJSON[IDResponse](data)
}

func (s *UsersService) Activate(ctx context.Context, userID int64) (*IDResponse, error) {
	data, err := s.c.post(ctx, fmt.Sprintf("/api/v1/users/%s/activate", strconv.FormatInt(userID, 10)), nil)
	if err != nil {
		return nil, err
	}
	return decodeJSON[IDResponse](data)
}

func (s *UsersService) Deactivate(ctx context.Context, userID int64) (*IDResponse, error) {
	data, err := s.c.post(ctx, fmt.Sprintf("/api/v1/users/%s/deactivate", strconv.FormatInt(userID, 10)), nil)
	if err != nil {
		return nil, err
	}
	return decodeJSON[IDResponse](data)
}

type RegionsService struct{ c *Client }

func (s *RegionsService) Create(ctx context.Context, req *CreateRegionRequest) (*IDResponse, error) {
	data, err := s.c.post(ctx, "/api/v1/regions/create", req)
	if err != nil {
		return nil, err
	}
	return decodeJSON[IDResponse](data)
}

func (s *RegionsService) List(ctx context.Context, opts *ListOptions) (*PaginatedResponse[Region], error) {
	q := url.Values{}
	if opts != nil {
		addPagination(q, opts.Page, opts.Limit)
	}
	path := "/api/v1/regions/list"
	if qs := q.Encode(); qs != "" {
		path += "?" + qs
	}
	data, err := s.c.get(ctx, path)
	if err != nil {
		return nil, err
	}
	return decodeJSON[PaginatedResponse[Region]](data)
}

func (s *RegionsService) Get(ctx context.Context, regionID int64) (*Region, error) {
	data, err := s.c.get(ctx, fmt.Sprintf("/api/v1/regions/%s", strconv.FormatInt(regionID, 10)))
	if err != nil {
		return nil, err
	}
	return decodeJSON[Region](data)
}

func (s *RegionsService) Edit(ctx context.Context, regionID int64, req *EditRegionRequest) (*IDResponse, error) {
	data, err := s.c.put(ctx, fmt.Sprintf("/api/v1/regions/%s/edit", strconv.FormatInt(regionID, 10)), req)
	if err != nil {
		return nil, err
	}
	return decodeJSON[IDResponse](data)
}

func (s *RegionsService) Activate(ctx context.Context, regionID int64) (*IDResponse, error) {
	data, err := s.c.post(ctx, fmt.Sprintf("/api/v1/regions/%s/activate", strconv.FormatInt(regionID, 10)), nil)
	if err != nil {
		return nil, err
	}
	return decodeJSON[IDResponse](data)
}

func (s *RegionsService) Deactivate(ctx context.Context, regionID int64) (*IDResponse, error) {
	data, err := s.c.post(ctx, fmt.Sprintf("/api/v1/regions/%s/deactivate", strconv.FormatInt(regionID, 10)), nil)
	if err != nil {
		return nil, err
	}
	return decodeJSON[IDResponse](data)
}

type StoragesService struct{ c *Client }

func (s *StoragesService) Create(ctx context.Context, req *CreateStorageRequest) (*IDResponse, error) {
	data, err := s.c.post(ctx, "/api/v1/storages/create", req)
	if err != nil {
		return nil, err
	}
	return decodeJSON[IDResponse](data)
}

func (s *StoragesService) List(ctx context.Context, opts *StorageListOptions) (*PaginatedResponse[Storage], error) {
	q := url.Values{}
	if opts != nil {
		q.Set("accountId", strconv.FormatInt(opts.AccountID, 10))
		addPagination(q, opts.Page, opts.Limit)
	}
	data, err := s.c.get(ctx, "/api/v1/storages/list"+"?"+q.Encode())
	if err != nil {
		return nil, err
	}
	return decodeJSON[PaginatedResponse[Storage]](data)
}

func (s *StoragesService) Get(ctx context.Context, storageID int64) (*Storage, error) {
	data, err := s.c.get(ctx, fmt.Sprintf("/api/v1/storages/%s", strconv.FormatInt(storageID, 10)))
	if err != nil {
		return nil, err
	}
	return decodeJSON[Storage](data)
}

func (s *StoragesService) Edit(ctx context.Context, storageID int64, req *EditStorageRequest) (*IDResponse, error) {
	data, err := s.c.put(ctx, fmt.Sprintf("/api/v1/storages/%s/edit", strconv.FormatInt(storageID, 10)), req)
	if err != nil {
		return nil, err
	}
	return decodeJSON[IDResponse](data)
}

func (s *StoragesService) Activate(ctx context.Context, storageID int64) (*IDResponse, error) {
	data, err := s.c.post(ctx, fmt.Sprintf("/api/v1/storages/%s/activate", strconv.FormatInt(storageID, 10)), nil)
	if err != nil {
		return nil, err
	}
	return decodeJSON[IDResponse](data)
}

func (s *StoragesService) Deactivate(ctx context.Context, storageID int64) (*IDResponse, error) {
	data, err := s.c.post(ctx, fmt.Sprintf("/api/v1/storages/%s/deactivate", strconv.FormatInt(storageID, 10)), nil)
	if err != nil {
		return nil, err
	}
	return decodeJSON[IDResponse](data)
}

type VolumesService struct{ c *Client }

func (s *VolumesService) UpdateQuota(ctx context.Context, volumeID int64, req *UpdateVolumeQuotaRequest) (*IDResponse, error) {
	data, err := s.c.put(ctx, fmt.Sprintf("/api/v1/volumes/%s/quota", strconv.FormatInt(volumeID, 10)), req)
	if err != nil {
		return nil, err
	}
	return decodeJSON[IDResponse](data)
}

type AuditLogsService struct{ c *Client }

func (s *AuditLogsService) List(ctx context.Context, opts *AuditLogListOptions) (*CursorPaginatedResponse[AuditLog], error) {
	q := url.Values{}
	if opts != nil {
		if opts.AccountID > 0 {
			q.Set("accountId", strconv.FormatInt(opts.AccountID, 10))
		}
		if opts.Cursor > 0 {
			q.Set("cursor", strconv.FormatInt(opts.Cursor, 10))
		}
		if opts.Limit > 0 {
			q.Set("limit", strconv.Itoa(opts.Limit))
		}
		if opts.Subject != "" {
			q.Set("subject", opts.Subject)
		}
	}
	path := "/api/v1/audit-logs/list"
	if qs := q.Encode(); qs != "" {
		path += "?" + qs
	}
	data, err := s.c.get(ctx, path)
	if err != nil {
		return nil, err
	}
	return decodeJSON[CursorPaginatedResponse[AuditLog]](data)
}

type ServiceNodesService struct{ c *Client }

func (s *ServiceNodesService) List(ctx context.Context, regionID int64) ([]ServiceNode, error) {
	data, err := s.c.get(ctx, fmt.Sprintf("/api/v1/regions/%s/nodes", strconv.FormatInt(regionID, 10)))
	if err != nil {
		return nil, err
	}
	result, err := decodeJSON[[]ServiceNode](data)
	if err != nil {
		return nil, err
	}
	return *result, nil
}

func (s *ServiceNodesService) Drain(ctx context.Context, regionID int64, nodeID string) error {
	_, err := s.c.post(ctx, fmt.Sprintf("/api/v1/regions/%s/nodes/%s/drain", strconv.FormatInt(regionID, 10), url.PathEscape(nodeID)), nil)
	return err
}

func (s *ServiceNodesService) Activate(ctx context.Context, regionID int64, nodeID string) error {
	_, err := s.c.post(ctx, fmt.Sprintf("/api/v1/regions/%s/nodes/%s/activate", strconv.FormatInt(regionID, 10), url.PathEscape(nodeID)), nil)
	return err
}

func (s *ServiceNodesService) Remove(ctx context.Context, regionID int64, nodeID string) error {
	_, err := s.c.delete(ctx, fmt.Sprintf("/api/v1/regions/%s/nodes/%s", strconv.FormatInt(regionID, 10), url.PathEscape(nodeID)))
	return err
}

type DiscoverService struct{ c *Client }

func (s *DiscoverService) Meta(ctx context.Context, accessKeyID string) (*DiscoverMetaResponse, error) {
	q := url.Values{}
	q.Set("access_key_id", accessKeyID)
	data, err := s.c.get(ctx, "/api/v1/discover/meta"+"?"+q.Encode())
	if err != nil {
		return nil, err
	}
	return decodeJSON[DiscoverMetaResponse](data)
}

type CacheService struct{ c *Client }

func (s *CacheService) Refresh(ctx context.Context) error {
	_, err := s.c.post(ctx, "/api/v1/cache/refresh", nil)
	return err
}
