// Code generated by gen; DO NOT EDIT.

package sdk

import "encoding/json"

// Config holds client configuration.
type Config struct {
	BaseURL    string
	PrivateKey string // base64-encoded 64-byte ED25519 private key
}

// ListOptions for page-based pagination.
type ListOptions struct {
	Page  int
	Limit int
}

// PaginationMeta from paginated responses.
type PaginationMeta struct {
	Page       int   `json:"page"`
	Limit      int   `json:"limit"`
	Total      int64 `json:"total"`
	TotalPages int64 `json:"totalPages"`
}

// PaginatedResponse wraps page-based results.
type PaginatedResponse[T any] struct {
	Items      []T            `json:"items"`
	Pagination PaginationMeta `json:"pagination"`
}

// CursorPaginatedResponse wraps cursor-based results.
type CursorPaginatedResponse[T any] struct {
	Items      []T    `json:"items"`
	NextCursor *int64 `json:"nextCursor"`
}

// IDResponse returned by create/edit/toggle endpoints.
type IDResponse struct {
	ID int64 `json:"id"`
}
type LicenseStatus = string

const (
	LicenseStatusValid LicenseStatus = "valid"
	LicenseStatusExpiring LicenseStatus = "expiring"
	LicenseStatusGrace LicenseStatus = "grace"
	LicenseStatusExpired LicenseStatus = "expired"
)


type Account struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
	IconURL     string         `json:"iconUrl,omitempty"`
	VendorInfo  map[string]any `json:"vendorInfo,omitempty"`
	LiveVolume  int64          `json:"liveVolume"`
	TotalVolume int64          `json:"totalVolume"`
	IsActive    bool           `json:"isActive"`
	Locked      bool           `json:"locked"`
	CreatedAt   string         `json:"createdAt"`
	UpdatedAt   string         `json:"updatedAt"`
}

type User struct {
	ID        int64  `json:"id"`
	AccountID int64  `json:"accountId"`
	Username  string `json:"username"`
	Email     string `json:"email"`
	Name      string `json:"name"`
	IsActive  bool   `json:"isActive"`
}

type Region struct {
	ID          int64  `json:"id"`
	ExportID    string `json:"exportId"`
	AccountID   int64  `json:"accountId"`
	Name        string `json:"name"`
	DNS         string `json:"dns"`
	LiveVolume  int64  `json:"liveVolume"`
	TotalVolume int64  `json:"totalVolume"`
	IsActive    bool   `json:"isActive"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}

type Storage struct {
	ID           int64  `json:"id"`
	Account      Ref    `json:"account"`
	RegionInfo   Ref    `json:"regionInfo"`
	Name         string `json:"name"`
	Description  string `json:"description,omitempty"`
	StorageType  string `json:"storageType"`
	ProviderType string `json:"providerType"`
	BlockType    string `json:"blockType,omitempty"`
	Endpoint     string `json:"endpoint"`
	Region       string `json:"region,omitempty"`
	Bucket       string `json:"bucket,omitempty"`
	Base         string `json:"base,omitempty"`
	BlockRegion  string `json:"blockRegion,omitempty"`
	BlockSize    int32  `json:"blockSize,omitempty"`
	IsActive     bool   `json:"isActive"`
	CreatedAt    string `json:"createdAt"`
	UpdatedAt    string `json:"updatedAt"`
}

type Volume struct {
	ID                      int64  `json:"id"`
	Account                 Ref    `json:"account"`
	Storage                 Ref    `json:"storage"`
	Region                  Ref    `json:"region"`
	Name                    string `json:"name"`
	Description             string `json:"description,omitempty"`
	Encryption              bool   `json:"encryption"`
	QuotaLimit              int64  `json:"quotaLimit"`
	LiveVolume              int64  `json:"liveVolume"`
	TotalVolume             int64  `json:"totalVolume"`
	PendingVolume           int64  `json:"pendingVolume"`
	Locked                  bool   `json:"locked"`
	RetentionPeriod         int32  `json:"retentionPeriod"`
	GracePeriod             int32  `json:"gracePeriod"`
	IsActive                bool   `json:"isActive"`
	IsCleanupMetaEnabled    bool   `json:"isCleanupMetaEnabled"`
	IsCleanupStorageEnabled bool   `json:"isCleanupStorageEnabled"`
	IsCleanupVaultEnabled   bool   `json:"isCleanupVaultEnabled"`
	CreatedAt               string `json:"createdAt"`
	UpdatedAt               string `json:"updatedAt"`
}

type Fork struct {
	Fid           int32  `json:"fid"`
	Name          string `json:"name"`
	ParentFid     int32  `json:"parentFid"`
	ParentName    string `json:"parentName"`
	SnapshotTs    int64  `json:"snapshotTs"`
	CreatedBy     string `json:"createdBy,omitempty"`
	CreatedAt     int64  `json:"createdAt"`
	ChildrenCount int32  `json:"childrenCount"`
}

type AuditLog struct {
	ID          int64           `json:"id"`
	Title       string          `json:"title"`
	Description string          `json:"description,omitempty"`
	Subject     string          `json:"subject,omitempty"`
	Success     bool            `json:"success"`
	Data        json.RawMessage `json:"data,omitempty"`
	CreatedBy   string          `json:"createdBy,omitempty"`
	AccountID   int64           `json:"accountId,omitempty"`
	CreatedAt   string          `json:"createdAt,omitempty"`
	UpdatedAt   string          `json:"updatedAt,omitempty"`
}

type ServiceNode struct {
	ID            int64          `json:"id"`
	RegionID      int64          `json:"regionId"`
	ServiceType   string         `json:"serviceType"`
	NodeID        string         `json:"nodeId"`
	AdvertiseAddr string         `json:"advertiseAddr"`
	RpcAddr       string         `json:"rpcAddr,omitempty"`
	Metadata      map[string]any `json:"metadata,omitempty"`
	Status        string         `json:"status"`
	LastHeartbeat int64          `json:"lastHeartbeat,omitempty"`
	IsActive      bool           `json:"isActive"`
	MemUsage      float64        `json:"memUsage,omitempty"`
	LoadAvg       float64        `json:"loadAvg,omitempty"`
}

type ClientSession struct {
	ID              int64           `json:"id"`
	Account         Ref             `json:"account"`
	Region          Ref             `json:"region"`
	Volume          Ref             `json:"volume"`
	User            Ref             `json:"user,omitempty"`
	ClientType      string          `json:"clientType"`
	OsName          string          `json:"osName"`
	OsVersion       string          `json:"osVersion,omitempty"`
	AppVersion      string          `json:"appVersion,omitempty"`
	Hostname        string          `json:"hostname,omitempty"`
	IPAddr          string          `json:"ipAddr"`
	MountMode       string          `json:"mountMode,omitempty"`
	MountPath       string          `json:"mountPath,omitempty"`
	ForkName        string          `json:"forkName,omitempty"`
	IsTemporaryFork bool            `json:"isTemporaryFork"`
	Metadata        json.RawMessage `json:"metadata,omitempty"`
	Metrics         json.RawMessage `json:"metrics,omitempty"`
	Status          string          `json:"status"`
	LastHeartbeat   int64           `json:"lastHeartbeat,omitempty"`
	ConnectedAt     int64           `json:"connectedAt,omitempty"`
	DisconnectedAt  int64           `json:"disconnectedAt,omitempty"`
	IsActive        bool            `json:"isActive"`
}

type SessionSummary struct {
	ClientType string `json:"clientType"`
	Status     string `json:"status"`
	Count      int64  `json:"count"`
}

type DiscoverMetaResponse struct {
	RegionID  int64              `json:"regionId"`
	Region    string             `json:"region"`
	Endpoints []DiscoverEndpoint `json:"endpoints"`
}

type DashboardStats struct {
	UserCount          int64                 `json:"userCount"`
	VolumeCount        int64                 `json:"volumeCount"`
	RegionCount        int64                 `json:"regionCount"`
	StorageCount       int64                 `json:"storageCount"`
	TotalVolumeUsed    int64                 `json:"totalVolumeUsed"`
	TotalQuotaLimit    int64                 `json:"totalQuotaLimit"`
	ActiveSessionCount int64                 `json:"activeSessionCount"`
	RegionBreakdown    []RegionVolumeMetrics `json:"regionBreakdown"`
}

type LicenseDetails struct {
	LicenseID       string        `json:"licenseId"`
	Licensee        string        `json:"licensee"`
	Contact         string        `json:"contact"`
	LicenseType     string        `json:"licenseType"`
	IssuedAt        string        `json:"issuedAt"`
	ExpiresAt       string        `json:"expiresAt"`
	GracePeriodDays int           `json:"gracePeriodDays"`
	MaxNodes        int64         `json:"maxNodes"`
	MaxVolumes      int64         `json:"maxVolumes"`
	MaxUsers        int64         `json:"maxUsers"`
	MaxStorageBytes int64         `json:"maxStorageBytes"`
	Status          LicenseStatus `json:"status"`
	DaysRemaining   int           `json:"daysRemaining"`
	GraceEndsAt     string        `json:"graceEndsAt"`
	GraceDaysLeft   int           `json:"graceDaysLeft"`
}

type ServiceAlert struct {
	ID          int64  `json:"id"`
	AlertID     string `json:"alertId"`
	Source      string `json:"source"`
	NodeID      string `json:"nodeId"`
	Severity    int    `json:"severity"`
	Category    string `json:"category"`
	Title       string `json:"title"`
	Description string `json:"description,omitempty"`
	RegionID    int64  `json:"regionId,omitempty"`
	AccountID   int64  `json:"accountId,omitempty"`
	EventTime   string `json:"eventTime"`
	ResolvedAt  string `json:"resolvedAt,omitempty"`
	CreatedAt   string `json:"createdAt,omitempty"`
}

type AlertCountResponse struct {
	Active        int64 `json:"active"`
	Recent        int64 `json:"recent"`
	InfoCount     int64 `json:"infoCount"`
	WarningCount  int64 `json:"warningCount"`
	CriticalCount int64 `json:"criticalCount"`
}

type DiscoverEndpoint struct {
	NodeID string `json:"nodeId"`
	Addr   string `json:"addr"`
	Status string `json:"status"`
}

type Ref struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type RegionVolumeMetrics struct {
	RegionID        int64  `json:"regionId"`
	RegionName      string `json:"regionName"`
	VolumeCount     int64  `json:"volumeCount"`
	TotalVolumeUsed int64  `json:"totalVolumeUsed"`
	TotalQuotaLimit int64  `json:"totalQuotaLimit"`
}

// Accounts

type CreateAccountRequest struct {
	Name        string         `json:"name"`
	Description string         `json:"description,omitempty"`
	IconURL     string         `json:"iconUrl,omitempty"`
	VendorInfo  map[string]any `json:"vendorInfo,omitempty"`
}

type EditAccountRequest struct {
	Name        string         `json:"name"`
	Description string         `json:"description,omitempty"`
	IconURL     string         `json:"iconUrl,omitempty"`
	VendorInfo  map[string]any `json:"vendorInfo,omitempty"`
}

// Users

type AddUserRequest struct {
	AccountID  int64          `json:"accountId"`
	Username   string         `json:"username"`
	Email      string         `json:"email"`
	Name       string         `json:"name,omitempty"`
	VendorInfo map[string]any `json:"vendorInfo,omitempty"`
}

type EditUserRequest struct {
	Username   string         `json:"username"`
	Email      string         `json:"email"`
	Name       string         `json:"name,omitempty"`
	VendorInfo map[string]any `json:"vendorInfo,omitempty"`
}

type UserListOptions struct {
	AccountID int64
	Search    string
	Page      int
	Limit     int
}

// Regions

type CreateRegionRequest struct {
	AccountID int64  `json:"accountId"`
	Name      string `json:"name"`
	DNS       string `json:"dns"`
}

type EditRegionRequest struct {
	AccountID int64  `json:"accountId"`
	Name      string `json:"name"`
	DNS       string `json:"dns"`
}

// Storages

type CreateStorageRequest struct {
	AccountID    int64  `json:"accountId"`
	RegionID     int64  `json:"regionId"`
	Name         string `json:"name"`
	Description  string `json:"description,omitempty"`
	StorageType  string `json:"storageType"`
	ProviderType string `json:"providerType"`
	Endpoint     string `json:"endpoint"`
	Region       string `json:"region,omitempty"`
	Bucket       string `json:"bucket,omitempty"`
	Base         string `json:"base,omitempty"`
	BlockRegion  string `json:"blockRegion,omitempty"`
	BlockType    string `json:"blockType,omitempty"`
	BlockSize    int32  `json:"blockSize,omitempty"`
	AccessKey    string `json:"accessKey,omitempty"`
	SecretKey    string `json:"secretKey,omitempty"`
}

type EditStorageRequest struct {
	Name        string `json:"name"`
	Description string `json:"description,omitempty"`
	Endpoint    string `json:"endpoint,omitempty"`
	AccessKey   string `json:"accessKey,omitempty"`
	SecretKey   string `json:"secretKey,omitempty"`
}

type TestStorageBucketRequest struct {
	Endpoint     string `json:"endpoint"`
	Region       string `json:"region,omitempty"`
	Bucket       string `json:"bucket"`
	AccessKey    string `json:"accessKey"`
	SecretKey    string `json:"secretKey"`
	ProviderType string `json:"providerType,omitempty"`
}

type TestBucketStorageResponse struct {
	BucketExists bool `json:"bucketExists"`
	List         bool `json:"list"`
	Write        bool `json:"write"`
	Read         bool `json:"read"`
	Delete       bool `json:"delete"`
	Multipart    bool `json:"multipart"`
}

type TestStorageBucketStorageResponse struct {
	BucketExists bool `json:"bucketExists"`
	List         bool `json:"list"`
	Write        bool `json:"write"`
	Read         bool `json:"read"`
	Delete       bool `json:"delete"`
	Multipart    bool `json:"multipart"`
}

type StorageListOptions struct {
	AccountID    int64
	Search       string
	RegionID     *int64
	StorageType  string
	ProviderType string
	Page         int
	Limit        int
}

// Volumes

type CreateVolumeRequest struct {
	AccountID       int64  `json:"accountId"`
	StorageID       int64  `json:"storageId"`
	Name            string `json:"name"`
	Description     string `json:"description,omitempty"`
	VolumeType      string `json:"volumeType"`
	Encryption      bool   `json:"encryption,omitempty"`
	EncryptionKey   string `json:"encryptionKey,omitempty"`
	RetentionPeriod int32  `json:"retentionPeriod,omitempty"`
	GracePeriod     int32  `json:"gracePeriod,omitempty"`
	QuotaLimit      int64  `json:"quotaLimit,omitempty"`
}

type CreateVolumeResponse struct {
	ID            int64  `json:"id"`
	EncryptionKey string `json:"encryptionKey,omitempty"`
}

type EditVolumeRequest struct {
	Description     string `json:"description,omitempty"`
	RetentionPeriod int32  `json:"retentionPeriod,omitempty"`
	GracePeriod     int32  `json:"gracePeriod,omitempty"`
}

type DeactivateVolumeRequest struct {
	IsCleanupMetaEnabled    bool `json:"isCleanupMetaEnabled,omitempty"`
	IsCleanupStorageEnabled bool `json:"isCleanupStorageEnabled,omitempty"`
	IsCleanupVaultEnabled   bool `json:"isCleanupVaultEnabled,omitempty"`
}

type GenerateVolumeAPIKeysRequest struct {
	UserID int64 `json:"userId"`
}

type GenerateAPIKeysVolumeResponse struct {
	APIKey    string `json:"apiKey"`
	APISecret string `json:"apiSecret"`
}

type RevokeVolumeAPIKeyRequest struct {
	APIKey string `json:"apiKey"`
}

type RevokeVolumeAPIKeysByUserRequest struct {
	UserID int64 `json:"userId"`
}

type UpdateVolumeQuotaRequest struct {
	QuotaLimit int64 `json:"quotaLimit"`
}

type StatsVolumeResponse struct {
	VolumeID      string `json:"volumeId"`
	LiveVolume    int64  `json:"liveVolume"`
	TotalVolume   int64  `json:"totalVolume"`
	PendingVolume int64  `json:"pendingVolume"`
}

type VolumeListOptions struct {
	AccountID int64
	RegionID  *int64
	StorageID *int64
	Page      int
	Limit     int
}

// AuditLogs

type AuditLogListOptions struct {
	AccountID *int64
	Cursor    int64
	Limit     int
	Subject   string
}

// RegionAuditLogs

type RegionAuditLogListOptions struct {
	Cursor  int64
	Limit   int
	Subject string
}

// ServiceNodes

// Nodes

// ClientSessions

type ClientSessionListOptions struct {
	AccountID  *int64
	RegionID   *int64
	VolumeID   *int64
	UserID     *int64
	ClientType string
	Status     string
	IsActive   string
	Page       int
	Limit      int
}

// Discover

// Dashboard

// License

// Alerts

type AlertListOptions struct {
	Active    *bool
	AccountID *int64
	RegionID  *int64
	Severity  *int
	Category  string
	Since     string
	Page      int
	Limit     int
}

// Cache
