// Code generated by gen; DO NOT EDIT.

package sdk

import "encoding/json"

// Config holds client configuration.
type Config struct {
	BaseURL    string
	PrivateKey string // base64-encoded 64-byte ED25519 private key
}

// ListOptions for page-based pagination.
type ListOptions struct {
	Page  int
	Limit int
}

// PaginationMeta from paginated responses.
type PaginationMeta struct {
	Page       int   `json:"page"`
	Limit      int   `json:"limit"`
	Total      int64 `json:"total"`
	TotalPages int64 `json:"totalPages"`
}

// PaginatedResponse wraps page-based results.
type PaginatedResponse[T any] struct {
	Items      []T            `json:"items"`
	Pagination PaginationMeta `json:"pagination"`
}

// CursorPaginatedResponse wraps cursor-based results.
type CursorPaginatedResponse[T any] struct {
	Items      []T    `json:"items"`
	NextCursor *int64 `json:"nextCursor"`
}

// IDResponse returned by create/edit/toggle endpoints.
type IDResponse struct {
	ID int64 `json:"id"`
}

type Account struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
	VendorInfo  map[string]any `json:"vendorInfo,omitempty"`
	IsActive    bool           `json:"isActive"`
	Locked      bool           `json:"locked"`
	CreatedAt   string         `json:"createdAt"`
	UpdatedAt   string         `json:"updatedAt"`
}

type User struct {
	ID        int64  `json:"id"`
	AccountID int64  `json:"accountId"`
	Username  string `json:"username"`
	Email     string `json:"email"`
	Name      string `json:"name"`
}

type Region struct {
	ID        int64  `json:"id"`
	ExportID  string `json:"exportId"`
	AccountID int64  `json:"accountId"`
	Name      string `json:"name"`
	IsActive  bool   `json:"isActive"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type Storage struct {
	ID           int64  `json:"id"`
	AccountID    int64  `json:"accountId"`
	RegionID     int64  `json:"regionId"`
	Name         string `json:"name"`
	Description  string `json:"description,omitempty"`
	StorageType  string `json:"storageType"`
	ProviderType string `json:"providerType"`
	BlockType    string `json:"blockType,omitempty"`
	Endpoint     string `json:"endpoint"`
	Region       string `json:"region,omitempty"`
	Bucket       string `json:"bucket,omitempty"`
	Base         string `json:"base,omitempty"`
	BlockRegion  string `json:"blockRegion,omitempty"`
	BlockSize    int32  `json:"blockSize,omitempty"`
	IsActive     bool   `json:"isActive"`
	CreatedAt    string `json:"createdAt"`
	UpdatedAt    string `json:"updatedAt"`
}

type Volume struct {
	ID          int64  `json:"id"`
	AccountID   int64  `json:"accountId"`
	StorageID   int64  `json:"storageId"`
	RegionID    int64  `json:"regionId"`
	Name        string `json:"name"`
	Description string `json:"description,omitempty"`
	Encryption  bool   `json:"encryption"`
	QuotaLimit  int64  `json:"quotaLimit"`
	QuotaUsed   int64  `json:"quotaUsed"`
	Locked      bool   `json:"locked"`
	IsActive    bool   `json:"isActive"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}

type AuditLog struct {
	ID          int64           `json:"id"`
	Title       string          `json:"title"`
	Description string          `json:"description,omitempty"`
	Subject     string          `json:"subject,omitempty"`
	Success     bool            `json:"success"`
	Data        json.RawMessage `json:"data,omitempty"`
	CreatedBy   string          `json:"createdBy,omitempty"`
	AccountID   int64           `json:"accountId,omitempty"`
	CreatedAt   string          `json:"createdAt,omitempty"`
	UpdatedAt   string          `json:"updatedAt,omitempty"`
}

type ServiceNode struct {
	ID            int64          `json:"id"`
	RegionID      int64          `json:"regionId"`
	ServiceType   string         `json:"serviceType"`
	NodeID        string         `json:"nodeId"`
	AdvertiseAddr string         `json:"advertiseAddr"`
	HTTPAddr      string         `json:"httpAddr,omitempty"`
	Metadata      map[string]any `json:"metadata,omitempty"`
	Status        string         `json:"status"`
	LastHeartbeat string         `json:"lastHeartbeat,omitempty"`
	IsActive      bool           `json:"isActive"`
}

type DiscoverMetaResponse struct {
	RegionID  int64              `json:"regionId"`
	Region    string             `json:"region"`
	Endpoints []DiscoverEndpoint `json:"endpoints"`
}

type DiscoverEndpoint struct {
	NodeID string `json:"nodeId"`
	Addr   string `json:"addr"`
	Status string `json:"status"`
}

// Accounts

type CreateAccountRequest struct {
	Name        string         `json:"name"`
	Description string         `json:"description,omitempty"`
	VendorInfo  map[string]any `json:"vendorInfo,omitempty"`
}

type EditAccountRequest struct {
	Name        string         `json:"name"`
	Description string         `json:"description,omitempty"`
	VendorInfo  map[string]any `json:"vendorInfo,omitempty"`
}

// Users

type AddUserRequest struct {
	AccountID  int64          `json:"accountId"`
	Username   string         `json:"username"`
	Email      string         `json:"email"`
	Name       string         `json:"name,omitempty"`
	VendorInfo map[string]any `json:"vendorInfo,omitempty"`
}

type EditUserRequest struct {
	Username   string         `json:"username"`
	Email      string         `json:"email"`
	Name       string         `json:"name,omitempty"`
	VendorInfo map[string]any `json:"vendorInfo,omitempty"`
}

type UserListOptions struct {
	AccountID int64
	Page      int
	Limit     int
}

// Regions

type CreateRegionRequest struct {
	AccountID int64  `json:"accountId"`
	Name      string `json:"name"`
}

type EditRegionRequest struct {
	AccountID int64  `json:"accountId"`
	Name      string `json:"name"`
}

// Storages

type CreateStorageRequest struct {
	AccountID    int64  `json:"accountId"`
	RegionID     int64  `json:"regionId"`
	Name         string `json:"name"`
	Description  string `json:"description,omitempty"`
	StorageType  string `json:"storageType"`
	ProviderType string `json:"providerType"`
	Endpoint     string `json:"endpoint"`
	Region       string `json:"region,omitempty"`
	Bucket       string `json:"bucket,omitempty"`
	Base         string `json:"base,omitempty"`
	BlockRegion  string `json:"blockRegion,omitempty"`
	BlockType    string `json:"blockType,omitempty"`
	BlockSize    int32  `json:"blockSize,omitempty"`
	AccessKey    string `json:"accessKey,omitempty"`
	SecretKey    string `json:"secretKey,omitempty"`
}

type EditStorageRequest struct {
	Name        string `json:"name"`
	Description string `json:"description,omitempty"`
	Endpoint    string `json:"endpoint,omitempty"`
	AccessKey   string `json:"accessKey,omitempty"`
	SecretKey   string `json:"secretKey,omitempty"`
}

type StorageListOptions struct {
	AccountID int64
	Page      int
	Limit     int
}

// Volumes

type CreateVolumeRequest struct {
	AccountID        int64  `json:"accountId"`
	StorageID        int64  `json:"storageId"`
	Name             string `json:"name"`
	Description      string `json:"description,omitempty"`
	VolumeType       string `json:"volumeType"`
	Encryption       bool   `json:"encryption,omitempty"`
	EncryptionKey    string `json:"encryptionKey,omitempty"`
	RetentionPeriod  int32  `json:"retentionPeriod,omitempty"`
	GracePeriod      int32  `json:"gracePeriod,omitempty"`
	GcOnDeactivation bool   `json:"gcOnDeactivation,omitempty"`
	QuotaLimit       int64  `json:"quotaLimit,omitempty"`
}

type CreateVolumeResponse struct {
	ID            int64  `json:"id"`
	EncryptionKey string `json:"encryptionKey,omitempty"`
}

type EditVolumeRequest struct {
	Name             string `json:"name"`
	Description      string `json:"description,omitempty"`
	Encryption       bool   `json:"encryption,omitempty"`
	RetentionPeriod  int32  `json:"retentionPeriod,omitempty"`
	GracePeriod      int32  `json:"gracePeriod,omitempty"`
	GcOnDeactivation bool   `json:"gcOnDeactivation,omitempty"`
}

type GenerateVolumeAPIKeysRequest struct {
	UserID int64 `json:"userId"`
}

type GenerateAPIKeysVolumeResponse struct {
	APIKey    string `json:"apiKey"`
	APISecret string `json:"apiSecret"`
}

type RevokeVolumeAPIKeyRequest struct {
	APIKey string `json:"apiKey"`
}

type UpdateVolumeQuotaRequest struct {
	QuotaLimit int64 `json:"quotaLimit"`
}

type StatsVolumeResponse struct {
	VolumeID   string `json:"volumeId"`
	DiskSize   int64  `json:"diskSize"`
	ActiveSize int64  `json:"activeSize"`
	Size       int64  `json:"size"`
}

type VolumeListOptions struct {
	AccountID int64
	Page      int
	Limit     int
}

// AuditLogs

type AuditLogListOptions struct {
	AccountID int64
	Cursor    int64
	Limit     int
	Subject   string
}

// ServiceNodes

// Discover

// Cache
