// Code generated by gen; DO NOT EDIT.

import type {
  ListOptions, PaginatedResponse, CursorPaginatedResponse,
  CreateAccountRequest, Account, AccountListOptions, EditAccountRequest, 
  UpdateAccountQuotaRequest, AddUserRequest, User, UserListOptions, BulkUserRequest, 
  UserLite, EditUserRequest, CreateRegionRequest, Region, RegionListOptions, 
  EditRegionRequest, RegionCluster, ClusterListOptions, CreateRegionClusterRequest, 
  RegionClusterListOptions, EditRegionClusterRequest, SetRegionClusterReadyRequest, 
  CreateStorageRequest, BlockMember, Storage, StorageListOptions, BlockVolume, 
  EditStorageRequest, TestStorageBucketRequest, CompatibleStorage, 
  MoveStorageVolumesRequest, MoveVolumeFailure, BackfillFailure, CreateVolumeRequest, 
  Volume, VolumeListOptions, EditVolumeRequest, MoveVolumeClusterRequest, 
  DeactivateVolumeRequest, GenerateVolumeAPIKeysRequest, VolumeApiKey, 
  RevokeVolumeAPIKeyRequest, RevokeVolumeAPIKeysByUserRequest, GenerateVolumeSttKeyRequest, 
  UpdateVolumeQuotaRequest, VolumeSizePoint, CreateVolumeForkRequest, Fork, 
  DeleteVolumeForkRequest, RestoreVolumeForkRequest, ForkTreeEntry, 
  VolumeForkTreeListOptions, ForkEntryDetail, ForkEntryVersion, VolumeForkEntryListOptions, 
  ForkTreeMatch, VolumeForkSearchListOptions, AuditLog, AuditLogListOptions, 
  RegionAuditLogListOptions, ServiceNode, NodeStatsSample, ClientSession, 
  ClientSessionListOptions, SessionSummary, DiscoverMetaResponse, DashboardStats, 
  LicenseDetails, LicenseTerms, LoadLicenseRequest, LicenseLoadResult, LicenseList, 
  ServiceAlert, AlertListOptions, AlertCountResponse, RegionAlert, RegionAlertListOptions,
} from './types_gen.js'

export type RequestFn = <T>(method: string, path: string, body?: unknown, signal?: AbortSignal) => Promise<T>

interface Client { request: RequestFn }

function queryString(params: Record<string, string | number | boolean | undefined>): string {
  const entries = Object.entries(params).filter(([, v]) => v !== undefined)
  if (entries.length === 0) return ''
  return '?' + entries.map(([k, v]) => `${k}=${encodeURIComponent(v!)}`).join('&')
}

export interface AdminClient {
  readonly accounts: AccountsResource
  readonly users: UsersResource
  readonly regions: RegionsResource
  readonly clusters: ClustersResource
  readonly regionClusters: RegionClustersResource
  readonly storages: StoragesResource
  readonly volumes: VolumesResource
  readonly volumeForkTrees: VolumeForkTreesResource
  readonly volumeForkEntries: VolumeForkEntriesResource
  readonly volumeForkSearches: VolumeForkSearchesResource
  readonly auditLogs: AuditLogsResource
  readonly regionAuditLogs: RegionAuditLogsResource
  readonly serviceNodes: ServiceNodesResource
  readonly nodes: NodesResource
  readonly clientSessions: ClientSessionsResource
  readonly discover: DiscoverResource
  readonly dashboard: DashboardResource
  readonly license: LicenseResource
  readonly alerts: AlertsResource
  readonly regionAlerts: RegionAlertsResource
  readonly vault: VaultResource
}

export function createClient(request: RequestFn): AdminClient {
  const client: Client = { request }
  let _accounts: AccountsResource | undefined
  let _users: UsersResource | undefined
  let _regions: RegionsResource | undefined
  let _clusters: ClustersResource | undefined
  let _regionClusters: RegionClustersResource | undefined
  let _storages: StoragesResource | undefined
  let _volumes: VolumesResource | undefined
  let _volumeForkTrees: VolumeForkTreesResource | undefined
  let _volumeForkEntries: VolumeForkEntriesResource | undefined
  let _volumeForkSearches: VolumeForkSearchesResource | undefined
  let _auditLogs: AuditLogsResource | undefined
  let _regionAuditLogs: RegionAuditLogsResource | undefined
  let _serviceNodes: ServiceNodesResource | undefined
  let _nodes: NodesResource | undefined
  let _clientSessions: ClientSessionsResource | undefined
  let _discover: DiscoverResource | undefined
  let _dashboard: DashboardResource | undefined
  let _license: LicenseResource | undefined
  let _alerts: AlertsResource | undefined
  let _regionAlerts: RegionAlertsResource | undefined
  let _vault: VaultResource | undefined
  return {
    get accounts() { return _accounts ??= new AccountsResource(client) },
    get users() { return _users ??= new UsersResource(client) },
    get regions() { return _regions ??= new RegionsResource(client) },
    get clusters() { return _clusters ??= new ClustersResource(client) },
    get regionClusters() { return _regionClusters ??= new RegionClustersResource(client) },
    get storages() { return _storages ??= new StoragesResource(client) },
    get volumes() { return _volumes ??= new VolumesResource(client) },
    get volumeForkTrees() { return _volumeForkTrees ??= new VolumeForkTreesResource(client) },
    get volumeForkEntries() { return _volumeForkEntries ??= new VolumeForkEntriesResource(client) },
    get volumeForkSearches() { return _volumeForkSearches ??= new VolumeForkSearchesResource(client) },
    get auditLogs() { return _auditLogs ??= new AuditLogsResource(client) },
    get regionAuditLogs() { return _regionAuditLogs ??= new RegionAuditLogsResource(client) },
    get serviceNodes() { return _serviceNodes ??= new ServiceNodesResource(client) },
    get nodes() { return _nodes ??= new NodesResource(client) },
    get clientSessions() { return _clientSessions ??= new ClientSessionsResource(client) },
    get discover() { return _discover ??= new DiscoverResource(client) },
    get dashboard() { return _dashboard ??= new DashboardResource(client) },
    get license() { return _license ??= new LicenseResource(client) },
    get alerts() { return _alerts ??= new AlertsResource(client) },
    get regionAlerts() { return _regionAlerts ??= new RegionAlertsResource(client) },
    get vault() { return _vault ??= new VaultResource(client) },
  }
}

export class AccountsResource {
  constructor(private client: Client) {}

  create(req: CreateAccountRequest, signal?: AbortSignal): Promise<{ id: number }> {
    return this.client.request('POST', '/api/v1/accounts/create', req, signal)
  }

  list(opts?: AccountListOptions, signal?: AbortSignal): Promise<PaginatedResponse<Account>> {
    return this.client.request('GET', `/api/v1/accounts/list${queryString({ isActive: opts?.isActive, page: opts?.page, limit: opts?.limit })}`, undefined, signal)
  }

  get(accountId: number, signal?: AbortSignal): Promise<Account> {
    return this.client.request('GET', `/api/v1/accounts/${accountId}`, undefined, signal)
  }

  edit(accountId: number, req: EditAccountRequest, signal?: AbortSignal): Promise<{ id: number }> {
    return this.client.request('PUT', `/api/v1/accounts/${accountId}/edit`, req, signal)
  }

  lock(accountId: number, signal?: AbortSignal): Promise<{ id: number }> {
    return this.client.request('POST', `/api/v1/accounts/${accountId}/lock`, undefined, signal)
  }

  unlock(accountId: number, signal?: AbortSignal): Promise<{ id: number }> {
    return this.client.request('POST', `/api/v1/accounts/${accountId}/unlock`, undefined, signal)
  }

  deactivate(accountId: number, signal?: AbortSignal): Promise<{ id: number }> {
    return this.client.request('POST', `/api/v1/accounts/${accountId}/deactivate`, undefined, signal)
  }

  updateQuota(accountId: number, req: UpdateAccountQuotaRequest, signal?: AbortSignal): Promise<{ id: number }> {
    return this.client.request('PUT', `/api/v1/accounts/${accountId}/quota`, req, signal)
  }
}

export class UsersResource {
  constructor(private client: Client) {}

  add(req: AddUserRequest, signal?: AbortSignal): Promise<{ id: number }> {
    return this.client.request('POST', '/api/v1/users/add', req, signal)
  }

  list(opts: UserListOptions, signal?: AbortSignal): Promise<PaginatedResponse<User>> {
    return this.client.request('GET', `/api/v1/users/list${queryString({ accountId: opts.accountId, search: opts.search, isActive: opts.isActive, page: opts.page, limit: opts.limit })}`, undefined, signal)
  }

  get(userId: number, signal?: AbortSignal): Promise<User> {
    return this.client.request('GET', `/api/v1/users/${userId}`, undefined, signal)
  }

  bulk(req: BulkUserRequest, signal?: AbortSignal): Promise<{ users: UserLite[] }> {
    return this.client.request('POST', '/api/v1/users/bulk', req, signal)
  }

  edit(userId: number, req: EditUserRequest, signal?: AbortSignal): Promise<{ id: number }> {
    return this.client.request('PUT', `/api/v1/users/${userId}/edit`, req, signal)
  }

  deactivate(userId: number, signal?: AbortSignal): Promise<{ id: number }> {
    return this.client.request('POST', `/api/v1/users/${userId}/deactivate`, undefined, signal)
  }
}

export class RegionsResource {
  constructor(private client: Client) {}

  create(req: CreateRegionRequest, signal?: AbortSignal): Promise<{ id: number }> {
    return this.client.request('POST', '/api/v1/regions/create', req, signal)
  }

  list(opts: RegionListOptions, signal?: AbortSignal): Promise<PaginatedResponse<Region>> {
    return this.client.request('GET', `/api/v1/regions/list${queryString({ accountId: opts.accountId, isActive: opts.isActive, page: opts.page, limit: opts.limit })}`, undefined, signal)
  }

  get(regionId: number, signal?: AbortSignal): Promise<Region> {
    return this.client.request('GET', `/api/v1/regions/${regionId}`, undefined, signal)
  }

  edit(regionId: number, req: EditRegionRequest, signal?: AbortSignal): Promise<{ id: number }> {
    return this.client.request('PUT', `/api/v1/regions/${regionId}/edit`, req, signal)
  }

  deactivate(regionId: number, signal?: AbortSignal): Promise<{ id: number }> {
    return this.client.request('POST', `/api/v1/regions/${regionId}/deactivate`, undefined, signal)
  }
}

export class ClustersResource {
  constructor(private client: Client) {}

  list(opts: ClusterListOptions, signal?: AbortSignal): Promise<PaginatedResponse<RegionCluster>> {
    return this.client.request('GET', `/api/v1/clusters/list${queryString({ accountId: opts.accountId, regionId: opts.regionId, isActive: opts.isActive, page: opts.page, limit: opts.limit })}`, undefined, signal)
  }
}

export class RegionClustersResource {
  constructor(private client: Client) {}

  create(regionId: number, req: CreateRegionClusterRequest, signal?: AbortSignal): Promise<{ id: number }> {
    return this.client.request('POST', `/api/v1/regions/${regionId}/clusters/create`, req, signal)
  }

  list(regionId: number, opts?: RegionClusterListOptions, signal?: AbortSignal): Promise<PaginatedResponse<RegionCluster>> {
    return this.client.request('GET', `/api/v1/regions/${regionId}/clusters/list` + queryString({ isActive: opts?.isActive, page: opts?.page, limit: opts?.limit }), undefined, signal)
  }

  get(regionId: number, clusterId: number, signal?: AbortSignal): Promise<RegionCluster> {
    return this.client.request('GET', `/api/v1/regions/${regionId}/clusters/${clusterId}`, undefined, signal)
  }

  edit(regionId: number, clusterId: number, req: EditRegionClusterRequest, signal?: AbortSignal): Promise<{ id: number }> {
    return this.client.request('PUT', `/api/v1/regions/${regionId}/clusters/${clusterId}/edit`, req, signal)
  }

  setDefault(regionId: number, clusterId: number, signal?: AbortSignal): Promise<{ id: number }> {
    return this.client.request('POST', `/api/v1/regions/${regionId}/clusters/${clusterId}/set-default`, undefined, signal)
  }

  setReady(regionId: number, clusterId: number, req: SetRegionClusterReadyRequest, signal?: AbortSignal): Promise<{ id: number; ready: boolean }> {
    return this.client.request('POST', `/api/v1/regions/${regionId}/clusters/${clusterId}/set-ready`, req, signal)
  }

  deactivate(regionId: number, clusterId: number, signal?: AbortSignal): Promise<{ id: number }> {
    return this.client.request('POST', `/api/v1/regions/${regionId}/clusters/${clusterId}/deactivate`, undefined, signal)
  }
}

export class StoragesResource {
  constructor(private client: Client) {}

  create(req: CreateStorageRequest, signal?: AbortSignal): Promise<{ id: number; blockVolumeIds?: string[] }> {
    return this.client.request('POST', '/api/v1/storages/create', req, signal)
  }

  list(opts: StorageListOptions, signal?: AbortSignal): Promise<PaginatedResponse<Storage>> {
    return this.client.request('GET', `/api/v1/storages/list${queryString({ accountId: opts.accountId, search: opts.search, regionId: opts.regionId, storageType: opts.storageType, providerType: opts.providerType, isActive: opts.isActive, directAccess: opts.directAccess, page: opts.page, limit: opts.limit })}`, undefined, signal)
  }

  get(storageId: number, signal?: AbortSignal): Promise<Storage> {
    return this.client.request('GET', `/api/v1/storages/${storageId}`, undefined, signal)
  }

  listBlockVolumes(storageId: number, signal?: AbortSignal): Promise<BlockVolume[]> {
    return this.client.request('GET', `/api/v1/storages/${storageId}/block-volumes`, undefined, signal)
  }

  edit(storageId: number, req: EditStorageRequest, signal?: AbortSignal): Promise<{ id: number }> {
    return this.client.request('PUT', `/api/v1/storages/${storageId}/edit`, req, signal)
  }

  deactivate(storageId: number, signal?: AbortSignal): Promise<{ id: number }> {
    return this.client.request('POST', `/api/v1/storages/${storageId}/deactivate`, undefined, signal)
  }

  testBucket(req: TestStorageBucketRequest, signal?: AbortSignal): Promise<{ bucketExists: boolean; list: boolean; write: boolean; read: boolean; delete: boolean; multipart: boolean }> {
    return this.client.request('POST', '/api/v1/storages/test-bucket', req, signal)
  }

  testStorageBucket(storageId: number, signal?: AbortSignal): Promise<{ bucketExists: boolean; list: boolean; write: boolean; read: boolean; delete: boolean; multipart: boolean }> {
    return this.client.request('POST', `/api/v1/storages/${storageId}/test-bucket`, undefined, signal)
  }

  listCompatible(storageId: number, signal?: AbortSignal): Promise<{ storages: CompatibleStorage[] }> {
    return this.client.request('GET', `/api/v1/storages/${storageId}/compatible`, undefined, signal)
  }

  moveVolumes(storageId: number, req: MoveStorageVolumesRequest, signal?: AbortSignal): Promise<{ moved: string[]; failures: MoveVolumeFailure[] }> {
    return this.client.request('POST', `/api/v1/storages/${storageId}/move-volumes`, req, signal)
  }

  backfillFingerprints(signal?: AbortSignal): Promise<{ scanned: number; updated: number; failures: BackfillFailure[]; hasMore: boolean }> {
    return this.client.request('POST', '/api/v1/storages/backfill-fingerprints', undefined, signal)
  }
}

export class VolumesResource {
  constructor(private client: Client) {}

  create(req: CreateVolumeRequest, signal?: AbortSignal): Promise<{ id: number; encryptionKey?: string }> {
    return this.client.request('POST', '/api/v1/volumes/create', req, signal)
  }

  list(opts: VolumeListOptions, signal?: AbortSignal): Promise<PaginatedResponse<Volume>> {
    return this.client.request('GET', `/api/v1/volumes/list${queryString({ accountId: opts.accountId, regionId: opts.regionId, regionClusterId: opts.regionClusterId, storageId: opts.storageId, volumeType: opts.volumeType, locked: opts.locked, isActive: opts.isActive, page: opts.page, limit: opts.limit })}`, undefined, signal)
  }

  get(volumeId: number, signal?: AbortSignal): Promise<Volume> {
    return this.client.request('GET', `/api/v1/volumes/${volumeId}`, undefined, signal)
  }

  edit(volumeId: number, req: EditVolumeRequest, signal?: AbortSignal): Promise<{ id: number }> {
    return this.client.request('PUT', `/api/v1/volumes/${volumeId}/edit`, req, signal)
  }

  lock(volumeId: number, signal?: AbortSignal): Promise<{ id: number }> {
    return this.client.request('POST', `/api/v1/volumes/${volumeId}/lock`, undefined, signal)
  }

  unlock(volumeId: number, signal?: AbortSignal): Promise<{ id: number }> {
    return this.client.request('POST', `/api/v1/volumes/${volumeId}/unlock`, undefined, signal)
  }

  moveCluster(volumeId: number, req: MoveVolumeClusterRequest, signal?: AbortSignal): Promise<{ id: number; sourceClusterId: number; targetClusterId: number; handoverUntil: number }> {
    return this.client.request('POST', `/api/v1/volumes/${volumeId}/move-cluster`, req, signal)
  }

  deactivate(volumeId: number, req: DeactivateVolumeRequest, signal?: AbortSignal): Promise<{ id: number }> {
    return this.client.request('POST', `/api/v1/volumes/${volumeId}/deactivate`, req, signal)
  }

  activate(volumeId: number, signal?: AbortSignal): Promise<{ id: number }> {
    return this.client.request('POST', `/api/v1/volumes/${volumeId}/activate`, undefined, signal)
  }

  generateAPIKeys(volumeId: number, req: GenerateVolumeAPIKeysRequest, signal?: AbortSignal): Promise<{ apiKey: string; apiSecret: string; evictedApiKeys?: string[] }> {
    return this.client.request('POST', `/api/v1/volumes/${volumeId}/api-keys/generate`, req, signal)
  }

  listAPIKeys(volumeId: number, signal?: AbortSignal): Promise<{ keys: VolumeApiKey[] }> {
    return this.client.request('GET', `/api/v1/volumes/${volumeId}/api-keys`, undefined, signal)
  }

  revokeAPIKey(volumeId: number, req: RevokeVolumeAPIKeyRequest, signal?: AbortSignal): Promise<void> {
    return this.client.request('POST', `/api/v1/volumes/${volumeId}/api-keys/revoke`, req, signal)
  }

  revokeAPIKeysByUser(volumeId: number, req: RevokeVolumeAPIKeysByUserRequest, signal?: AbortSignal): Promise<void> {
    return this.client.request('POST', `/api/v1/volumes/${volumeId}/api-keys/revoke-by-user`, req, signal)
  }

  generateSttKey(volumeId: number, req: GenerateVolumeSttKeyRequest, signal?: AbortSignal): Promise<{ apiKey: string; apiSecret: string; expiresAt: string }> {
    return this.client.request('POST', `/api/v1/volumes/${volumeId}/stt-key/generate`, req, signal)
  }

  updateQuota(volumeId: number, req: UpdateVolumeQuotaRequest, signal?: AbortSignal): Promise<{ id: number }> {
    return this.client.request('PUT', `/api/v1/volumes/${volumeId}/quota`, req, signal)
  }

  stats(volumeId: number, signal?: AbortSignal): Promise<{ volumeId: string; liveVolume: number; totalVolume: number; pendingVolume: number; liveInactiveVolume: number }> {
    return this.client.request('GET', `/api/v1/volumes/${volumeId}/stats`, undefined, signal)
  }

  sizeHistory(volumeId: number, from?: string, to?: string, signal?: AbortSignal): Promise<{ points: VolumeSizePoint[] }> {
    return this.client.request('GET', `/api/v1/volumes/${volumeId}/size-history${queryString({ from: from, to: to })}`, undefined, signal)
  }

  createFork(volumeId: number, req: CreateVolumeForkRequest, signal?: AbortSignal): Promise<Fork> {
    return this.client.request('POST', `/api/v1/volumes/${volumeId}/forks/create`, req, signal)
  }

  listForks(volumeId: number, volumeType?: string, signal?: AbortSignal): Promise<Fork[]> {
    return this.client.request('GET', `/api/v1/volumes/${volumeId}/forks${queryString({ volumeType: volumeType })}`, undefined, signal)
  }

  listAllForks(volumeId: number, volumeType?: string, signal?: AbortSignal): Promise<Fork[]> {
    return this.client.request('GET', `/api/v1/volumes/${volumeId}/forks${queryString({ include_inactive: "true", volumeType: volumeType })}`, undefined, signal)
  }

  deleteFork(volumeId: number, forkName: string, req: DeleteVolumeForkRequest, signal?: AbortSignal): Promise<{ inactivatedFids: number[] }> {
    return this.client.request('POST', `/api/v1/volumes/${volumeId}/forks/${forkName}/delete`, req, signal)
  }

  restoreFork(volumeId: number, forkName: string, req: RestoreVolumeForkRequest, signal?: AbortSignal): Promise<Fork> {
    return this.client.request('POST', `/api/v1/volumes/${volumeId}/forks/${forkName}/restore`, req, signal)
  }
}

export class VolumeForkTreesResource {
  constructor(private client: Client) {}

  list(volumeId: number, forkName: string, opts?: VolumeForkTreeListOptions, signal?: AbortSignal): Promise<CursorPaginatedResponse<ForkTreeEntry>> {
    return this.client.request('GET', `/api/v1/volumes/${volumeId}/forks/${forkName}/tree${queryString({
      path: opts?.path,
      asOf: opts?.asOf,
      cursor: opts?.cursor,
      limit: opts?.limit,
      sort: opts?.sort,
      kind: opts?.kind,
    })}`, undefined, signal)
  }
}

export class VolumeForkEntriesResource {
  constructor(private client: Client) {}

  get(volumeId: number, forkName: string, path?: string, inode?: number, asOf?: number, signal?: AbortSignal): Promise<ForkEntryDetail> {
    return this.client.request('GET', `/api/v1/volumes/${volumeId}/forks/${forkName}/entry${queryString({ path: path, inode: inode, asOf: asOf })}`, undefined, signal)
  }

  versions(volumeId: number, forkName: string, opts?: VolumeForkEntryListOptions, signal?: AbortSignal): Promise<CursorPaginatedResponse<ForkEntryVersion>> {
    return this.client.request('GET', `/api/v1/volumes/${volumeId}/forks/${forkName}/entry/versions${queryString({
      path: opts?.path,
      cursor: opts?.cursor,
      limit: opts?.limit,
    })}`, undefined, signal)
  }
}

export class VolumeForkSearchesResource {
  constructor(private client: Client) {}

  find(volumeId: number, forkName: string, opts?: VolumeForkSearchListOptions, signal?: AbortSignal): Promise<CursorPaginatedResponse<ForkTreeMatch>> {
    return this.client.request('GET', `/api/v1/volumes/${volumeId}/forks/${forkName}/search${queryString({
      q: opts?.q,
      path: opts?.path,
      asOf: opts?.asOf,
      exact: opts?.exact,
      cursor: opts?.cursor,
      limit: opts?.limit,
      kind: opts?.kind,
    })}`, undefined, signal)
  }
}

export class AuditLogsResource {
  constructor(private client: Client) {}

  list(opts: AuditLogListOptions, signal?: AbortSignal): Promise<CursorPaginatedResponse<AuditLog>> {
    return this.client.request('GET', `/api/v1/audit-logs/list${queryString({
      accountId: opts.accountId,
      regionId: opts.regionId,
      regionClusterId: opts.regionClusterId,
      cursor: opts.cursor,
      limit: opts.limit,
      subject: opts.subject,
    })}`, undefined, signal)
  }
}

export class RegionAuditLogsResource {
  constructor(private client: Client) {}

  list(regionId: number, opts?: RegionAuditLogListOptions, signal?: AbortSignal): Promise<CursorPaginatedResponse<AuditLog>> {
    return this.client.request('GET', `/api/v1/regions/${regionId}/audit-logs/list${queryString({
      regionClusterId: opts?.regionClusterId,
      cursor: opts?.cursor,
      limit: opts?.limit,
      subject: opts?.subject,
      node: opts?.node,
    })}`, undefined, signal)
  }
}

export class ServiceNodesResource {
  constructor(private client: Client) {}

  list(regionId: number, serviceType?: string, status?: string, inactiveHours?: number, regionClusterId?: number, signal?: AbortSignal): Promise<ServiceNode[]> {
    return this.client.request('GET', `/api/v1/regions/${regionId}/nodes${queryString({ serviceType: serviceType, status: status, inactiveHours: inactiveHours, regionClusterId: regionClusterId })}`, undefined, signal)
  }

  stats(regionId: number, nodeId: string, signal?: AbortSignal): Promise<string> {
    return this.client.request('GET', `/api/v1/regions/${regionId}/nodes/${encodeURIComponent(nodeId)}/stats`, undefined, signal)
  }

  statsHistory(regionId: number, nodeId: string, signal?: AbortSignal): Promise<{ intervalMs: number; samples: NodeStatsSample[] }> {
    return this.client.request('GET', `/api/v1/regions/${regionId}/nodes/${encodeURIComponent(nodeId)}/stats/history`, undefined, signal)
  }
}

export class NodesResource {
  constructor(private client: Client) {}

  listAll(accountId: number, serviceType?: string, status?: string, inactiveHours?: number, signal?: AbortSignal): Promise<ServiceNode[]> {
    return this.client.request('GET', `/api/v1/nodes${queryString({ accountId: accountId, serviceType: serviceType, status: status, inactiveHours: inactiveHours })}`, undefined, signal)
  }
}

export class ClientSessionsResource {
  constructor(private client: Client) {}

  list(opts: ClientSessionListOptions, signal?: AbortSignal): Promise<PaginatedResponse<ClientSession>> {
    return this.client.request('GET', `/api/v1/client-sessions/list${queryString({ accountId: opts.accountId, regionId: opts.regionId, regionClusterId: opts.regionClusterId, volumeId: opts.volumeId, userId: opts.userId, clientType: opts.clientType, status: opts.status, isActive: opts.isActive, osName: opts.osName, platform: opts.platform, search: opts.search, page: opts.page, limit: opts.limit })}`, undefined, signal)
  }

  get(sessionId: number, signal?: AbortSignal): Promise<ClientSession> {
    return this.client.request('GET', `/api/v1/client-sessions/${sessionId}`, undefined, signal)
  }

  summary(accountId: number, regionId?: number, regionClusterId?: number, volumeId?: number, userId?: number, signal?: AbortSignal): Promise<SessionSummary> {
    return this.client.request('GET', `/api/v1/client-sessions/summary${queryString({ accountId: accountId, regionId: regionId, regionClusterId: regionClusterId, volumeId: volumeId, userId: userId })}`, undefined, signal)
  }
}

export class DiscoverResource {
  constructor(private client: Client) {}

  meta(accessKeyId: string, signal?: AbortSignal): Promise<DiscoverMetaResponse> {
    return this.client.request('GET', `/api/v1/discover/meta${queryString({ access_key_id: accessKeyId })}`, undefined, signal)
  }
}

export class DashboardResource {
  constructor(private client: Client) {}

  stats(accountId: number, signal?: AbortSignal): Promise<DashboardStats> {
    return this.client.request('GET', `/api/v1/dashboard/stats${queryString({ accountId: accountId })}`, undefined, signal)
  }
}

export class LicenseResource {
  constructor(private client: Client) {}

  get(signal?: AbortSignal): Promise<LicenseDetails> {
    return this.client.request('GET', '/api/v1/license', undefined, signal)
  }

  terms(signal?: AbortSignal): Promise<LicenseTerms> {
    return this.client.request('GET', '/api/v1/license/terms', undefined, signal)
  }

  load(req: LoadLicenseRequest, signal?: AbortSignal): Promise<LicenseLoadResult> {
    return this.client.request('POST', '/api/v1/license/load', req, signal)
  }

  list(signal?: AbortSignal): Promise<LicenseList> {
    return this.client.request('GET', '/api/v1/license/list', undefined, signal)
  }
}

export class AlertsResource {
  constructor(private client: Client) {}

  list(opts?: AlertListOptions, signal?: AbortSignal): Promise<PaginatedResponse<ServiceAlert>> {
    return this.client.request('GET', `/api/v1/alerts/list${queryString({ active: opts?.active, accountId: opts?.accountId, regionId: opts?.regionId, severity: opts?.severity, category: opts?.category, since: opts?.since, page: opts?.page, limit: opts?.limit })}`, undefined, signal)
  }

  count(signal?: AbortSignal): Promise<AlertCountResponse> {
    return this.client.request('GET', '/api/v1/alerts/count', undefined, signal)
  }

  resolve(alertId: string, signal?: AbortSignal): Promise<void> {
    return this.client.request('POST', `/api/v1/alerts/${alertId}/resolve`, undefined, signal)
  }
}

export class RegionAlertsResource {
  constructor(private client: Client) {}

  list(regionId: number, opts?: RegionAlertListOptions, signal?: AbortSignal): Promise<PaginatedResponse<RegionAlert>> {
    return this.client.request('GET', `/api/v1/regions/${regionId}/alerts/list` + queryString({ active: opts?.active, severity: opts?.severity, category: opts?.category, nodeId: opts?.nodeId, regionClusterId: opts?.regionClusterId, since: opts?.since, page: opts?.page, limit: opts?.limit }), undefined, signal)
  }

  count(regionId: number, regionClusterId?: number, signal?: AbortSignal): Promise<AlertCountResponse> {
    return this.client.request('GET', `/api/v1/regions/${regionId}/alerts/count${queryString({ regionClusterId: regionClusterId })}`, undefined, signal)
  }

  resolve(regionId: number, alertId: string, signal?: AbortSignal): Promise<void> {
    return this.client.request('POST', `/api/v1/regions/${regionId}/alerts/${alertId}/resolve`, undefined, signal)
  }
}

export class VaultResource {
  constructor(private client: Client) {}

  resync(signal?: AbortSignal): Promise<void> {
    return this.client.request('POST', '/api/v1/vault/resync', undefined, signal)
  }
}
