// Code generated by gen; DO NOT EDIT.

import { TokenSigner } from './auth.js'
import { MountOSError } from './errors.js'
import type {
  Config, StandardResponse, ListOptions,
  PaginatedResponse, CursorPaginatedResponse,
  CreateAccountRequest, Account, EditAccountRequest, AddUserRequest, User, UserListOptions, 
  EditUserRequest, CreateRegionRequest, Region, EditRegionRequest, CreateStorageRequest, 
  Storage, StorageListOptions, EditStorageRequest, TestStorageBucketRequest, 
  CreateVolumeRequest, Volume, VolumeListOptions, EditVolumeRequest, 
  GenerateVolumeAPIKeysRequest, RevokeVolumeAPIKeyRequest, UpdateVolumeQuotaRequest, 
  AuditLog, AuditLogListOptions, RegionAuditLogListOptions, ServiceNode, ClientSession, 
  ClientSessionListOptions, SessionSummary, DiscoverMetaResponse, DashboardStats, 
  LicenseDetails,
} from './types_gen.js'

function queryString(params: Record<string, string | number | undefined>): string {
  const entries = Object.entries(params).filter(([, v]) => v !== undefined)
  if (entries.length === 0) return ''
  return '?' + entries.map(([k, v]) => `${k}=${encodeURIComponent(v!)}`).join('&')
}

export class MountOSAdmin {
  private readonly baseUrl: string
  private readonly signer: TokenSigner

  private _accounts?: AccountsResource
  private _users?: UsersResource
  private _regions?: RegionsResource
  private _storages?: StoragesResource
  private _volumes?: VolumesResource
  private _auditLogs?: AuditLogsResource
  private _regionAuditLogs?: RegionAuditLogsResource
  private _serviceNodes?: ServiceNodesResource
  private _clientSessions?: ClientSessionsResource
  private _discover?: DiscoverResource
  private _dashboard?: DashboardResource
  private _license?: LicenseResource
  private _cache?: CacheResource

  constructor(config: Config) {
    this.baseUrl = config.baseUrl.replace(/\/+$/, '')
    this.signer = new TokenSigner(config.privateKey)
  }

  get accounts(): AccountsResource {
    return (this._accounts ??= new AccountsResource(this))
  }

  get users(): UsersResource {
    return (this._users ??= new UsersResource(this))
  }

  get regions(): RegionsResource {
    return (this._regions ??= new RegionsResource(this))
  }

  get storages(): StoragesResource {
    return (this._storages ??= new StoragesResource(this))
  }

  get volumes(): VolumesResource {
    return (this._volumes ??= new VolumesResource(this))
  }

  get auditLogs(): AuditLogsResource {
    return (this._auditLogs ??= new AuditLogsResource(this))
  }

  get regionAuditLogs(): RegionAuditLogsResource {
    return (this._regionAuditLogs ??= new RegionAuditLogsResource(this))
  }

  get serviceNodes(): ServiceNodesResource {
    return (this._serviceNodes ??= new ServiceNodesResource(this))
  }

  get clientSessions(): ClientSessionsResource {
    return (this._clientSessions ??= new ClientSessionsResource(this))
  }

  get discover(): DiscoverResource {
    return (this._discover ??= new DiscoverResource(this))
  }

  get dashboard(): DashboardResource {
    return (this._dashboard ??= new DashboardResource(this))
  }

  get license(): LicenseResource {
    return (this._license ??= new LicenseResource(this))
  }

  get cache(): CacheResource {
    return (this._cache ??= new CacheResource(this))
  }

  async request<T>(method: string, path: string, body?: unknown): Promise<T> {
    const token = await this.signer.getToken()
    const headers: Record<string, string> = {
      'Authorization': `Bearer ${token}`,
    }

    const init: RequestInit = { method, headers }
    if (body !== undefined) {
      headers['Content-Type'] = 'application/json'
      init.body = JSON.stringify(body)
    }

    const res = await fetch(`${this.baseUrl}${path}`, init)

    let json: StandardResponse<T>
    try {
      json = await res.json() as StandardResponse<T>
    } catch {
      throw new MountOSError(res.statusText || 'request failed', res.status)
    }

    if (json.status !== 'success') {
      throw new MountOSError(json.message, res.status, json.errorCode)
    }
    return json.data as T
  }
}

class AccountsResource {
  constructor(private client: MountOSAdmin) {}

  create(req: CreateAccountRequest): Promise<{ id: number }> {
    return this.client.request('POST', '/api/v1/accounts/create', req)
  }

  list(opts?: ListOptions): Promise<PaginatedResponse<Account>> {
    return this.client.request('GET', `/api/v1/accounts/list${queryString({ page: opts?.page, limit: opts?.limit })}`)
  }

  get(accountId: number): Promise<Account> {
    return this.client.request('GET', `/api/v1/accounts/${accountId}`)
  }

  edit(accountId: number, req: EditAccountRequest): Promise<{ id: number }> {
    return this.client.request('PUT', `/api/v1/accounts/${accountId}/edit`, req)
  }

  lock(accountId: number): Promise<{ id: number }> {
    return this.client.request('POST', `/api/v1/accounts/${accountId}/lock`)
  }

  unlock(accountId: number): Promise<{ id: number }> {
    return this.client.request('POST', `/api/v1/accounts/${accountId}/unlock`)
  }

  deactivate(accountId: number): Promise<{ id: number }> {
    return this.client.request('POST', `/api/v1/accounts/${accountId}/deactivate`)
  }
}

class UsersResource {
  constructor(private client: MountOSAdmin) {}

  add(req: AddUserRequest): Promise<{ id: number }> {
    return this.client.request('POST', '/api/v1/users/add', req)
  }

  list(opts: UserListOptions): Promise<PaginatedResponse<User>> {
    return this.client.request('GET', `/api/v1/users/list${queryString({ accountId: opts.accountId, page: opts.page, limit: opts.limit })}`)
  }

  get(userId: number): Promise<User> {
    return this.client.request('GET', `/api/v1/users/${userId}`)
  }

  edit(userId: number, req: EditUserRequest): Promise<{ id: number }> {
    return this.client.request('PUT', `/api/v1/users/${userId}/edit`, req)
  }

  deactivate(userId: number): Promise<{ id: number }> {
    return this.client.request('POST', `/api/v1/users/${userId}/deactivate`)
  }
}

class RegionsResource {
  constructor(private client: MountOSAdmin) {}

  create(req: CreateRegionRequest): Promise<{ id: number }> {
    return this.client.request('POST', '/api/v1/regions/create', req)
  }

  list(opts?: ListOptions): Promise<PaginatedResponse<Region>> {
    return this.client.request('GET', `/api/v1/regions/list${queryString({ page: opts?.page, limit: opts?.limit })}`)
  }

  get(regionId: number): Promise<Region> {
    return this.client.request('GET', `/api/v1/regions/${regionId}`)
  }

  edit(regionId: number, req: EditRegionRequest): Promise<{ id: number }> {
    return this.client.request('PUT', `/api/v1/regions/${regionId}/edit`, req)
  }

  deactivate(regionId: number): Promise<{ id: number }> {
    return this.client.request('POST', `/api/v1/regions/${regionId}/deactivate`)
  }
}

class StoragesResource {
  constructor(private client: MountOSAdmin) {}

  create(req: CreateStorageRequest): Promise<{ id: number }> {
    return this.client.request('POST', '/api/v1/storages/create', req)
  }

  list(opts: StorageListOptions): Promise<PaginatedResponse<Storage>> {
    return this.client.request('GET', `/api/v1/storages/list${queryString({ accountId: opts.accountId, page: opts.page, limit: opts.limit })}`)
  }

  get(storageId: number): Promise<Storage> {
    return this.client.request('GET', `/api/v1/storages/${storageId}`)
  }

  edit(storageId: number, req: EditStorageRequest): Promise<{ id: number }> {
    return this.client.request('PUT', `/api/v1/storages/${storageId}/edit`, req)
  }

  deactivate(storageId: number): Promise<{ id: number }> {
    return this.client.request('POST', `/api/v1/storages/${storageId}/deactivate`)
  }

  testBucket(req: TestStorageBucketRequest): Promise<{ bucketExists: boolean; list: boolean; write: boolean; read: boolean; delete: boolean; multipart: boolean }> {
    return this.client.request('POST', '/api/v1/storages/test-bucket', req)
  }

  testStorageBucket(storageId: number): Promise<{ bucketExists: boolean; list: boolean; write: boolean; read: boolean; delete: boolean; multipart: boolean }> {
    return this.client.request('POST', `/api/v1/storages/${storageId}/test-bucket`)
  }
}

class VolumesResource {
  constructor(private client: MountOSAdmin) {}

  create(req: CreateVolumeRequest): Promise<{ id: number; encryptionKey: string }> {
    return this.client.request('POST', '/api/v1/volumes/create', req)
  }

  list(opts: VolumeListOptions): Promise<PaginatedResponse<Volume>> {
    return this.client.request('GET', `/api/v1/volumes/list${queryString({ accountId: opts.accountId, page: opts.page, limit: opts.limit })}`)
  }

  get(volumeId: number): Promise<Volume> {
    return this.client.request('GET', `/api/v1/volumes/${volumeId}`)
  }

  edit(volumeId: number, req: EditVolumeRequest): Promise<{ id: number }> {
    return this.client.request('PUT', `/api/v1/volumes/${volumeId}/edit`, req)
  }

  lock(volumeId: number): Promise<{ id: number }> {
    return this.client.request('POST', `/api/v1/volumes/${volumeId}/lock`)
  }

  unlock(volumeId: number): Promise<{ id: number }> {
    return this.client.request('POST', `/api/v1/volumes/${volumeId}/unlock`)
  }

  deactivate(volumeId: number): Promise<{ id: number }> {
    return this.client.request('POST', `/api/v1/volumes/${volumeId}/deactivate`)
  }

  generateAPIKeys(volumeId: number, req: GenerateVolumeAPIKeysRequest): Promise<{ apiKey: string; apiSecret: string }> {
    return this.client.request('POST', `/api/v1/volumes/${volumeId}/api-keys/generate`, req)
  }

  revokeAPIKey(volumeId: number, req: RevokeVolumeAPIKeyRequest): Promise<void> {
    return this.client.request('POST', `/api/v1/volumes/${volumeId}/api-keys/revoke`, req)
  }

  updateQuota(volumeId: number, req: UpdateVolumeQuotaRequest): Promise<{ id: number }> {
    return this.client.request('PUT', `/api/v1/volumes/${volumeId}/quota`, req)
  }

  stats(volumeId: number): Promise<{ volumeId: string; diskSize: number; activeSize: number; size: number }> {
    return this.client.request('GET', `/api/v1/volumes/${volumeId}/stats`)
  }
}

class AuditLogsResource {
  constructor(private client: MountOSAdmin) {}

  list(opts?: AuditLogListOptions): Promise<CursorPaginatedResponse<AuditLog>> {
    return this.client.request('GET', `/api/v1/audit-logs/list${queryString({
      accountId: opts?.accountId,
      cursor: opts?.cursor,
      limit: opts?.limit,
      subject: opts?.subject,
    })}`)
  }
}

class RegionAuditLogsResource {
  constructor(private client: MountOSAdmin) {}

  list(regionId: number, opts?: RegionAuditLogListOptions): Promise<CursorPaginatedResponse<AuditLog>> {
    return this.client.request('GET', `/api/v1/regions/${regionId}/audit-logs/list${queryString({
      cursor: opts?.cursor,
      limit: opts?.limit,
      subject: opts?.subject,
    })}`)
  }
}

class ServiceNodesResource {
  constructor(private client: MountOSAdmin) {}

  list(regionId: number, serviceType?: string, status?: string): Promise<ServiceNode[]> {
    return this.client.request('GET', `/api/v1/regions/${regionId}/nodes${queryString({ serviceType: serviceType, status: status })}`)
  }

  stats(regionId: number, nodeId: string): Promise<string> {
    return this.client.request('GET', `/api/v1/regions/${regionId}/nodes/${encodeURIComponent(nodeId)}/stats`)
  }
}

class ClientSessionsResource {
  constructor(private client: MountOSAdmin) {}

  list(opts?: ClientSessionListOptions): Promise<PaginatedResponse<ClientSession>> {
    return this.client.request('GET', `/api/v1/client-sessions/list${queryString({ accountId: opts?.accountId, regionId: opts?.regionId, clientType: opts?.clientType, status: opts?.status, page: opts?.page, limit: opts?.limit })}`)
  }

  get(sessionId: number): Promise<ClientSession> {
    return this.client.request('GET', `/api/v1/client-sessions/${sessionId}`)
  }

  summary(accountId?: number): Promise<SessionSummary[]> {
    return this.client.request('GET', `/api/v1/client-sessions/summary${queryString({ accountId: accountId })}`)
  }
}

class DiscoverResource {
  constructor(private client: MountOSAdmin) {}

  meta(accessKeyId: string): Promise<DiscoverMetaResponse> {
    return this.client.request('GET', `/api/v1/discover/meta${queryString({ access_key_id: accessKeyId })}`)
  }
}

class DashboardResource {
  constructor(private client: MountOSAdmin) {}

  stats(accountId: number): Promise<DashboardStats> {
    return this.client.request('GET', `/api/v1/dashboard/stats${queryString({ accountId: accountId })}`)
  }
}

class LicenseResource {
  constructor(private client: MountOSAdmin) {}

  get(): Promise<LicenseDetails> {
    return this.client.request('GET', '/api/v1/license')
  }
}

class CacheResource {
  constructor(private client: MountOSAdmin) {}

  refresh(): Promise<void> {
    return this.client.request('POST', '/api/v1/cache/refresh')
  }
}
