// Code generated by gen; DO NOT EDIT.

export interface Config {
  baseUrl: string
  privateKey: string
  dashboardUser?: DashboardUser
}

export interface StandardResponse<T = unknown> {
  status: 'success' | 'failure'
  message: string
  data?: T
  errorCode?: number
}

export interface PaginationMeta {
  page: number
  limit: number
  total: number
  totalPages: number
}

export interface PaginatedResponse<T> {
  items: T[]
  pagination: PaginationMeta
}

export interface CursorPaginatedResponse<T> {
  items: T[]
  nextCursor: number | null
}

export interface ListOptions {
  page?: number
  limit?: number
}

export type LicenseStatus = 'valid' | 'expiring' | 'grace' | 'expired'

export interface Account {
  id: number
  name: string
  description: string
  iconUrl?: string
  vendorInfo?: Record<string, unknown>
  liveVolume: number
  totalVolume: number
  isActive: boolean
  locked: boolean
  createdAt: string
  updatedAt: string
}

export interface User {
  id: number
  accountId: number
  username: string
  email: string
  name: string
  isActive: boolean
}

export interface Region {
  id: number
  exportId: string
  accountId: number
  name: string
  dns: string
  liveVolume: number
  totalVolume: number
  isActive: boolean
  createdAt: string
  updatedAt: string
}

export interface Storage {
  id: number
  account: Ref
  regionInfo: Ref
  name: string
  description?: string
  storageType: string
  providerType: string
  blockType?: string
  endpoint: string
  region?: string
  bucket?: string
  base?: string
  blockRegion?: string
  blockSize?: number
  isActive: boolean
  createdAt: string
  updatedAt: string
}

export interface Volume {
  id: number
  account: Ref
  storage: Ref
  region: Ref
  name: string
  description?: string
  encryption: boolean
  quotaLimit: number
  liveVolume: number
  totalVolume: number
  pendingVolume: number
  locked: boolean
  retentionPeriod: number
  gracePeriod: number
  isActive: boolean
  isCleanupMetaEnabled: boolean
  isCleanupStorageEnabled: boolean
  isCleanupVaultEnabled: boolean
  createdAt: string
  updatedAt: string
}

export interface Fork {
  fid: number
  name: string
  parentFid: number
  parentName: string
  snapshotTs: number
  createdBy?: string
  createdAt: number
  childrenCount: number
}

export interface AuditLog {
  id: number
  title: string
  description?: string
  subject?: string
  success: boolean
  data?: unknown
  createdBy?: string
  accountId?: number
  createdAt?: string
  updatedAt?: string
}

export interface ServiceNode {
  id: number
  regionId: number
  serviceType: string
  nodeId: string
  advertiseAddr: string
  rpcAddr?: string
  metadata?: Record<string, unknown>
  status: string
  lastHeartbeat?: number
  isActive: boolean
  memUsage?: number
  loadAvg?: number
}

export interface ClientSession {
  id: number
  account: Ref
  region: Ref
  volume: Ref
  user?: Ref
  clientType: string
  osName: string
  osVersion?: string
  appVersion?: string
  hostname?: string
  ipAddr: string
  mountMode?: string
  mountPath?: string
  forkName?: string
  isTemporaryFork: boolean
  metadata?: unknown
  metrics?: unknown
  status: string
  lastHeartbeat?: number
  connectedAt?: number
  disconnectedAt?: number
  isActive: boolean
}

export interface SessionSummary {
  clientType: string
  status: string
  count: number
}

export interface DiscoverMetaResponse {
  regionId: number
  region: string
  endpoints: DiscoverEndpoint[]
}

export interface DashboardStats {
  userCount: number
  volumeCount: number
  regionCount: number
  storageCount: number
  totalVolumeUsed: number
  totalQuotaLimit: number
  activeSessionCount: number
  regionBreakdown: RegionVolumeMetrics[]
}

export interface LicenseDetails {
  licenseId: string
  licensee: string
  contact: string
  licenseType: string
  issuedAt: string
  expiresAt: string
  gracePeriodDays: number
  maxNodes: number
  maxVolumes: number
  maxUsers: number
  maxStorageBytes: number
  status: LicenseStatus
  daysRemaining: number
  graceEndsAt: string
  graceDaysLeft: number
}

export interface LicenseTerms {
  terms: string
}

export interface ServiceAlert {
  id: number
  alertId: string
  source: string
  nodeId: string
  severity: number
  category: string
  title: string
  description?: string
  regionId?: number
  accountId?: number
  eventTime: string
  resolvedAt?: string
  createdAt?: string
}

export interface AlertCountResponse {
  active: number
  recent: number
  infoCount: number
  warningCount: number
  criticalCount: number
}

export interface DashboardUser {
  id: string
  name: string
  email?: string
  role: string
  username?: string
  accountId?: number
  userId?: number
  volumeId?: number
  exp?: number
}

export interface DiscoverEndpoint {
  nodeId: string
  addr: string
  status: string
}

export interface Ref {
  id: number
  name: string
}

export interface RegionVolumeMetrics {
  regionId: number
  regionName: string
  volumeCount: number
  totalVolumeUsed: number
  totalQuotaLimit: number
}

// Accounts

export interface CreateAccountRequest {
  name: string
  description?: string
  iconUrl?: string
  vendorInfo?: Record<string, unknown>
}

export interface EditAccountRequest {
  name: string
  description?: string
  iconUrl?: string
  vendorInfo?: Record<string, unknown>
}

// Users

export interface AddUserRequest {
  accountId: number
  username: string
  email: string
  name?: string
  vendorInfo?: Record<string, unknown>
}

export interface EditUserRequest {
  username: string
  email: string
  name?: string
  vendorInfo?: Record<string, unknown>
}

export interface UserListOptions extends ListOptions {
  accountId: number
  search?: string
}

// Regions

export interface CreateRegionRequest {
  accountId: number
  name: string
  dns: string
}

export interface EditRegionRequest {
  accountId: number
  name: string
  dns: string
}

// Storages

export interface CreateStorageRequest {
  accountId: number
  regionId: number
  name: string
  description?: string
  storageType: string
  providerType: string
  endpoint: string
  region?: string
  bucket?: string
  base?: string
  blockRegion?: string
  blockType?: string
  blockSize?: number
  accessKey?: string
  secretKey?: string
}

export interface EditStorageRequest {
  name: string
  description?: string
  endpoint?: string
  accessKey?: string
  secretKey?: string
}

export interface TestStorageBucketRequest {
  endpoint: string
  region?: string
  bucket: string
  accessKey: string
  secretKey: string
  providerType?: string
}

export interface StorageListOptions extends ListOptions {
  accountId: number
  search?: string
  regionId?: number
  storageType?: string
  providerType?: string
}

// Volumes

export interface CreateVolumeRequest {
  accountId: number
  storageId: number
  name: string
  description?: string
  volumeType: string
  encryption?: boolean
  encryptionKey?: string
  retentionPeriod?: number
  gracePeriod?: number
  quotaLimit?: number
}

export interface EditVolumeRequest {
  description?: string
  retentionPeriod?: number
  gracePeriod?: number
}

export interface DeactivateVolumeRequest {
  isCleanupMetaEnabled?: boolean
  isCleanupStorageEnabled?: boolean
  isCleanupVaultEnabled?: boolean
}

export interface GenerateVolumeAPIKeysRequest {
  userId: number
}

export interface RevokeVolumeAPIKeyRequest {
  apiKey: string
}

export interface RevokeVolumeAPIKeysByUserRequest {
  userId: number
}

export interface UpdateVolumeQuotaRequest {
  quotaLimit: number
}

export interface VolumeListOptions extends ListOptions {
  accountId: number
  regionId?: number
  storageId?: number
}

// AuditLogs

export interface AuditLogListOptions {
  accountId?: number
  cursor?: number
  limit?: number
  subject?: string
}

// RegionAuditLogs

export interface RegionAuditLogListOptions {
  cursor?: number
  limit?: number
  subject?: string
}

// ServiceNodes

// Nodes

// ClientSessions

export interface ClientSessionListOptions extends ListOptions {
  accountId?: number
  regionId?: number
  volumeId?: number
  userId?: number
  clientType?: string
  status?: string
  isActive?: string
}

// Discover

// Dashboard

// License

// Alerts

export interface AlertListOptions extends ListOptions {
  active?: boolean
  accountId?: number
  regionId?: number
  severity?: number
  category?: string
  since?: string
}

// Cache
