// Code generated by gen; DO NOT EDIT.

export interface Config {
  baseUrl: string
  privateKey: string
}

export interface StandardResponse<T = unknown> {
  status: 'success' | 'failure'
  message: string
  data?: T
  errorCode?: number
}

export interface PaginationMeta {
  page: number
  limit: number
  total: number
  totalPages: number
}

export interface PaginatedResponse<T> {
  items: T[]
  pagination: PaginationMeta
}

export interface CursorPaginatedResponse<T> {
  items: T[]
  nextCursor: number | null
}

export interface ListOptions {
  page?: number
  limit?: number
}

export interface Account {
  id: number
  name: string
  description: string
  iconUrl?: string
  vendorInfo?: Record<string, unknown>
  isActive: boolean
  locked: boolean
  createdAt: string
  updatedAt: string
}

export interface User {
  id: number
  accountId: number
  username: string
  email: string
  name: string
  isActive: boolean
}

export interface Region {
  id: number
  exportId: string
  accountId: number
  name: string
  dns: string
  isActive: boolean
  createdAt: string
  updatedAt: string
}

export interface Storage {
  id: number
  accountId: number
  regionId: number
  name: string
  description?: string
  storageType: string
  providerType: string
  blockType?: string
  endpoint: string
  region?: string
  bucket?: string
  base?: string
  blockRegion?: string
  blockSize?: number
  isActive: boolean
  createdAt: string
  updatedAt: string
}

export interface Volume {
  id: number
  accountId: number
  storageId: number
  regionId: number
  name: string
  description?: string
  encryption: boolean
  quotaLimit: number
  quotaUsed: number
  locked: boolean
  isActive: boolean
  createdAt: string
  updatedAt: string
}

export interface AuditLog {
  id: number
  title: string
  description?: string
  subject?: string
  success: boolean
  data?: unknown
  createdBy?: string
  accountId?: number
  createdAt?: string
  updatedAt?: string
}

export interface ServiceNode {
  id: number
  regionId: number
  serviceType: string
  nodeId: string
  advertiseAddr: string
  rpcAddr?: string
  metadata?: Record<string, unknown>
  status: string
  lastHeartbeat?: number
  isActive: boolean
}

export interface ClientSession {
  id: number
  accountId: number
  volumeId: string
  regionId: number
  userId?: string
  clientType: string
  osName: string
  osVersion?: string
  appVersion?: string
  hostname?: string
  ipAddr: string
  mountMode?: string
  mountPath?: string
  metadata?: unknown
  metrics?: unknown
  status: string
  lastHeartbeat?: number
  connectedAt?: number
  disconnectedAt?: number
  isActive: boolean
}

export interface SessionSummary {
  clientType: string
  status: string
  count: number
}

export interface DiscoverMetaResponse {
  regionId: number
  region: string
  endpoints: DiscoverEndpoint[]
}

export interface DashboardStats {
  userCount: number
  volumeCount: number
  regionCount: number
  storageCount: number
  totalQuotaUsed: number
  totalQuotaLimit: number
  activeSessionCount: number
  regionBreakdown: RegionVolumeMetrics[]
}

export interface LicenseDetails {
  licenseId: string
  licensee: string
  contact: string
  licenseType: string
  issuedAt: string
  expiresAt: string
  gracePeriodDays: number
  maxNodes: number
  maxVolumes: number
  maxUsers: number
  maxStorageBytes: number
  status: string
  daysRemaining: number
  graceEndsAt: string
  graceDaysLeft: number
}

export interface DiscoverEndpoint {
  nodeId: string
  addr: string
  status: string
}

export interface RegionVolumeMetrics {
  regionId: number
  regionName: string
  volumeCount: number
  totalQuotaUsed: number
  totalQuotaLimit: number
}

// Accounts

export interface CreateAccountRequest {
  name: string
  description?: string
  iconUrl?: string
  vendorInfo?: Record<string, unknown>
}

export interface EditAccountRequest {
  name: string
  description?: string
  iconUrl?: string
  vendorInfo?: Record<string, unknown>
}

// Users

export interface AddUserRequest {
  accountId: number
  username: string
  email: string
  name?: string
  vendorInfo?: Record<string, unknown>
}

export interface EditUserRequest {
  username: string
  email: string
  name?: string
  vendorInfo?: Record<string, unknown>
}

export interface UserListOptions extends ListOptions {
  accountId: number
}

// Regions

export interface CreateRegionRequest {
  accountId: number
  name: string
  dns: string
}

export interface EditRegionRequest {
  accountId: number
  name: string
  dns: string
}

// Storages

export interface CreateStorageRequest {
  accountId: number
  regionId: number
  name: string
  description?: string
  storageType: string
  providerType: string
  endpoint: string
  region?: string
  bucket?: string
  base?: string
  blockRegion?: string
  blockType?: string
  blockSize?: number
  accessKey?: string
  secretKey?: string
}

export interface EditStorageRequest {
  name: string
  description?: string
  endpoint?: string
  accessKey?: string
  secretKey?: string
}

export interface TestStorageBucketRequest {
  endpoint: string
  region?: string
  bucket: string
  accessKey: string
  secretKey: string
  providerType?: string
}

export interface StorageListOptions extends ListOptions {
  accountId: number
}

// Volumes

export interface CreateVolumeRequest {
  accountId: number
  storageId: number
  name: string
  description?: string
  volumeType: string
  encryption?: boolean
  encryptionKey?: string
  retentionPeriod?: number
  gracePeriod?: number
  gcOnDeactivation?: boolean
  quotaLimit?: number
}

export interface EditVolumeRequest {
  name: string
  description?: string
  encryption?: boolean
  retentionPeriod?: number
  gracePeriod?: number
  gcOnDeactivation?: boolean
}

export interface GenerateVolumeAPIKeysRequest {
  userId: number
}

export interface RevokeVolumeAPIKeyRequest {
  apiKey: string
}

export interface UpdateVolumeQuotaRequest {
  quotaLimit: number
}

export interface VolumeListOptions extends ListOptions {
  accountId: number
}

// AuditLogs

export interface AuditLogListOptions {
  accountId?: number
  cursor?: number
  limit?: number
  subject?: string
}

// ServiceNodes

export interface ServiceNodeListOptions {
  serviceType?: string
  status?: string
  inactiveHours?: number
}

// ClientSessions

export interface ClientSessionListOptions extends ListOptions {
  accountId?: number
  regionId?: number
  clientType?: string
  status?: string
}

// Discover

// Dashboard

// License

// Cache
