// Code generated by gen; DO NOT EDIT.

export interface Config {
  baseUrl: string
  privateKey: string
  dashboardUser?: DashboardUser
}

export interface StandardResponse<T = unknown> {
  status: 'success' | 'failure'
  message: string
  data?: T
  errorCode?: number
}

export interface PaginationMeta {
  page: number
  limit: number
  total: number
  totalPages: number
}

export interface PaginatedResponse<T> {
  items: T[]
  pagination: PaginationMeta
}

export interface CursorPaginatedResponse<T> {
  items: T[]
  nextCursor: number | null
}

export interface ListOptions {
  page?: number
  limit?: number
}

export type ClientSessionStatus = 'connected' | 'active' | 'unhealthy' | 'disconnected' | 'expired' | 'unknown'

export type LicenseQuotaState = 'ok' | 'exceeded'

export type LicenseStatus = 'valid' | 'expiring' | 'grace' | 'expired_access' | 'expired'

export interface Account {
  id: number
  name: string
  description: string
  iconUrl?: string
  providerInfo?: Record<string, unknown>
  liveVolume: number
  totalVolume: number
  isActive: boolean
  locked: boolean
  createdAt: string
  updatedAt: string
}

export interface User {
  id: number
  accountId: number
  username: string
  email: string
  name: string
  isActive: boolean
}

export interface Region {
  id: number
  exportId: string
  accountId: number
  name: string
  dns: string
  liveVolume: number
  totalVolume: number
  isActive: boolean
  createdAt: string
  updatedAt: string
}

export interface RegionCluster {
  id: number
  exportId: string
  regionId: number
  name: string
  defaultCluster: boolean
  isReady: boolean
  isActive: boolean
  createdAt: string
  updatedAt: string
}

export interface Storage {
  id: number
  account: Ref
  regionInfo: Ref
  name: string
  description?: string
  storageType: string
  providerType: string
  blockType?: string
  endpoint: string
  region?: string
  bucket?: string
  base?: string
  blockRegion?: string
  blockSize?: number
  isActive: boolean
  createdAt: string
  updatedAt: string
}

export interface Volume {
  id: number
  account: Ref
  storage: Ref
  region: Ref
  regionCluster?: Ref
  name: string
  description?: string
  volumeType: string
  encryption: boolean
  quotaLimit: number
  liveVolume: number
  totalVolume: number
  pendingVolume: number
  liveInactiveVolume: number
  locked: boolean
  retentionPeriod: number
  gracePeriod: number
  forkGracePeriod: number
  eventLogRetentionPeriod: number
  isActive: boolean
  isCleanupMetaEnabled: boolean
  isCleanupStorageEnabled: boolean
  isCleanupVaultEnabled: boolean
  createdAt: string
  updatedAt: string
}

export interface Fork {
  fid: number
  name: string
  parentFid: number
  parentName: string
  snapshotTs: number
  createdBy?: string
  createdAt: number
  childrenCount: number
  inactive?: boolean
  inactiveAt?: number
  status: string
  size: number
}

export interface ForkTreeEntry {
  inode: number
  name: string
  kind: string
  size: number
  mtime: number
  ctime: number
  creatorId?: number
  updaterId?: number
}

export interface ForkEntryDetail {
  inode: number
  path: string
  name: string
  kind: string
  size: number
  mtime: number
  ctime: number
  generation: number
  owner?: string
  mode?: number
  xattrs?: Record<string, unknown>
  creatorId?: number
  updaterId?: number
}

export interface ForkEntryVersion {
  generation: number
  size: number
  mtime: number
  updaterId?: number
  contentHash?: string
}

export interface ForkTreeMatch {
  path: string
  inode: number
  kind: string
  size: number
  mtime: number
}

export interface AuditLog {
  id: number
  title: string
  description?: string
  subject?: string
  success: boolean
  data?: unknown
  createdBy?: string
  node?: string
  accountId?: number
  regionId?: number
  regionClusterId?: number
  createdAt?: string
  updatedAt?: string
}

export interface ServiceNode {
  id: number
  regionId: number
  regionClusterId?: number
  serviceType: string
  nodeId: string
  advertiseAddr: string
  rpcAddr?: string
  metadata?: Record<string, unknown>
  status: string
  lastHeartbeat?: number
  isActive: boolean
  memUsage?: number
  sysLoad?: number
}

export interface ClientSession {
  id: number
  account: Ref
  region: Ref
  regionCluster?: Ref
  volume: Ref
  user?: Ref
  clientType: string
  osName: string
  osVersion?: string
  appVersion?: string
  hostname?: string
  ipAddr: string
  mountMode?: string
  mountPath?: string
  forkName?: string
  isTemporaryFork: boolean
  metadata?: unknown
  metrics?: unknown
  status: ClientSessionStatus
  lastHeartbeat?: number
  connectedAt?: number
  disconnectedAt?: number
  isActive: boolean
}

export interface SessionSummary {
  byStatus: SessionSummaryStatusEntry[]
  byPlatform: SessionSummaryFacet[]
  byOsName: SessionSummaryFacet[]
  regionCount: number
  volumeCount: number
  hostCount: number
  unhealthyCount: number
}

export interface DiscoverMetaResponse {
  regionId: number
  region: string
  endpoints: DiscoverEndpoint[]
}

export interface DashboardStats {
  userCount: number
  volumeCount: number
  regionCount: number
  storageCount: number
  totalVolumeUsed: number
  totalQuotaLimit: number
  activeSessionCount: number
  regionBreakdown: RegionVolumeMetrics[]
}

export interface LicenseDetails {
  licenseId: string
  licensee: string
  contact: string
  licenseType: string
  issuedAt: string
  expiresAt: string
  gracePeriodDays: number
  expiredAccessDays: number
  maxNodes: number
  maxVolumes: number
  maxUsers: number
  maxAccounts: number
  maxRegions: number
  maxStorageBytes: number
  status: LicenseStatus
  daysRemaining: number
  graceEndsAt: string
  graceDaysLeft: number
  expiredAccessEndsAt: string
  expiredAccessDaysLeft: number
  quota: LicenseQuota
}

export interface LicenseTerms {
  terms: string
}

export interface ServiceAlert {
  id: number
  alertId: string
  source: string
  nodeId: string
  severity: number
  category: string
  title: string
  description?: string
  region?: Ref
  account?: Ref
  eventTime: string
  resolvedAt?: string
  createdAt?: string
}

export interface AlertCountResponse {
  active: number
  recent: number
  infoCount: number
  warningCount: number
  criticalCount: number
}

export interface RegionAlert {
  id: number
  alertId: string
  source: string
  nodeId: string
  regionClusterId?: number
  severity: number
  category: string
  title: string
  description?: string
  eventTime: string
  resolvedAt?: string
  createdAt?: string
}

export interface DashboardUser {
  id: string
  name: string
  email?: string
  role: string
  username?: string
  accountId?: number
  userId?: number
  volumeId?: number
  exp?: number
}

export interface DiscoverEndpoint {
  nodeId: string
  addr: string
  status: string
}

export interface LicenseQuota {
  state: LicenseQuotaState
  liveVolume: number
  totalVolume: number
  generation: number
  lastTransitionAtMs: number
}

export interface Ref {
  id: number
  name: string
}

export interface RegionVolumeMetrics {
  regionId: number
  regionName: string
  volumeCount: number
  totalVolumeUsed: number
  totalQuotaLimit: number
}

export interface SessionSummaryFacet {
  label: string
  count: number
}

export interface SessionSummaryStatusEntry {
  clientType: string
  status: string
  count: number
}

export interface UserLite {
  id: number
  username: string
  name: string
}

export interface VolumeSizePoint {
  bucketEnd: string
  liveVolume: number
  totalVolume: number
  pendingVolume: number
  liveInactiveVolume: number
}

// Accounts

export interface CreateAccountRequest {
  name: string
  description?: string
  iconUrl?: string
  providerInfo?: Record<string, unknown>
}

export interface EditAccountRequest {
  name: string
  description?: string
  iconUrl?: string
  providerInfo?: Record<string, unknown>
}

export interface AccountListOptions extends ListOptions {
  isActive?: boolean
}

// Users

export interface AddUserRequest {
  accountId: number
  username: string
  email: string
  name?: string
  providerInfo?: Record<string, unknown>
}

export interface BulkUserRequest {
  ids: number[]
}

export interface EditUserRequest {
  username: string
  email: string
  name?: string
  providerInfo?: Record<string, unknown>
}

export interface UserListOptions extends ListOptions {
  accountId: number
  search?: string
  isActive?: boolean
}

// Regions

export interface CreateRegionRequest {
  accountId: number
  name: string
  dns: string
}

export interface EditRegionRequest {
  accountId: number
  name: string
  dns: string
}

export interface RegionListOptions extends ListOptions {
  isActive?: boolean
}

// RegionClusters

export interface CreateRegionClusterRequest {
  name: string
}

export interface EditRegionClusterRequest {
  name: string
}

export interface SetRegionClusterReadyRequest {
  ready: boolean
}

export interface RegionClusterListOptions extends ListOptions {
  isActive?: boolean
}

// Storages

export interface CreateStorageRequest {
  accountId: number
  regionId: number
  name: string
  description?: string
  storageType: string
  providerType: string
  endpoint: string
  region?: string
  bucket?: string
  base?: string
  blockRegion?: string
  blockType?: string
  blockSize?: number
  accessKey?: string
  secretKey?: string
}

export interface EditStorageRequest {
  name: string
  description?: string
  endpoint?: string
  accessKey?: string
  secretKey?: string
}

export interface TestStorageBucketRequest {
  endpoint: string
  region?: string
  bucket: string
  accessKey: string
  secretKey: string
  providerType?: string
}

export interface StorageListOptions extends ListOptions {
  accountId: number
  search?: string
  regionId?: number
  storageType?: string
  providerType?: string
  isActive?: boolean
}

// Volumes

export interface CreateVolumeRequest {
  accountId: number
  storageId: number
  name: string
  description?: string
  volumeType: string
  encryption?: boolean
  encryptionKey?: string
  retentionPeriod?: number
  gracePeriod?: number
  forkGracePeriod?: number
  eventLogRetentionPeriod?: number
  quotaLimit?: number
  regionClusterId?: number
  regionClusterUuid?: string
}

export interface EditVolumeRequest {
  description?: string
  retentionPeriod?: number
  gracePeriod?: number
  forkGracePeriod?: number
  eventLogRetentionPeriod?: number
}

export interface MoveVolumeClusterRequest {
  targetClusterId?: number
  targetClusterUuid?: string
}

export interface DeactivateVolumeRequest {
  isCleanupMetaEnabled?: boolean
  isCleanupStorageEnabled?: boolean
  isCleanupVaultEnabled?: boolean
}

export interface GenerateVolumeAPIKeysRequest {
  userId: number
}

export interface RevokeVolumeAPIKeyRequest {
  apiKey: string
}

export interface RevokeVolumeAPIKeysByUserRequest {
  userId: number
}

export interface UpdateVolumeQuotaRequest {
  quotaLimit: number
}

export interface CreateVolumeForkRequest {
  name: string
  parentName?: string
  asOf?: number
  volumeType?: string
}

export interface DeleteVolumeForkRequest {
  force?: boolean
  volumeType?: string
}

export interface RestoreVolumeForkRequest {
  volumeType?: string
}

export interface VolumeListOptions extends ListOptions {
  accountId: number
  regionId?: number
  regionClusterId?: number
  storageId?: number
  volumeType?: string
  locked?: boolean
  isActive?: boolean
}

// VolumeForkTrees

export interface VolumeForkTreeListOptions {
  path?: string
  asOf?: number
  cursor?: number
  limit?: number
  sort?: string
  kind?: string
}

// VolumeForkEntries

export interface VolumeForkEntryListOptions {
  path?: string
  cursor?: number
  limit?: number
}

// VolumeForkSearches

export interface VolumeForkSearchListOptions {
  q?: string
  path?: string
  asOf?: number
  exact?: boolean
  cursor?: number
  limit?: number
  kind?: string
}

// AuditLogs

export interface AuditLogListOptions {
  accountId?: number
  regionId?: number
  regionClusterId?: number
  cursor?: number
  limit?: number
  subject?: string
}

// RegionAuditLogs

export interface RegionAuditLogListOptions {
  regionClusterId?: number
  cursor?: number
  limit?: number
  subject?: string
  node?: string
}

// ServiceNodes

// Nodes

// ClientSessions

export interface ClientSessionListOptions extends ListOptions {
  accountId?: number
  regionId?: number
  regionClusterId?: number
  volumeId?: number
  userId?: number
  clientType?: string
  status?: ClientSessionStatus
  isActive?: string
  osName?: string
  platform?: string
  search?: string
}

// Discover

// Dashboard

// License

// Alerts

export interface AlertListOptions extends ListOptions {
  active?: boolean
  accountId?: number
  regionId?: number
  severity?: number
  category?: string
  since?: string
}

// RegionAlerts

export interface RegionAlertListOptions extends ListOptions {
  active?: boolean
  severity?: number
  category?: string
  nodeId?: string
  regionClusterId?: number
  since?: string
}

// Vault
